import type {
  Snapshot,
  SnapshotFile,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits pgmq-clients.mjs: one typed client per DETECTED pgmq queue.
// Queues are found from the pgmq schema's q_<name> tables when the
// snapshot includes that schema (add "pgmq" to `schemas` in the
// config). Methods wrap the extension's own SQL functions: send,
// sendBatch, read, pop, archive, delete.
//
// Honest limit, stated up front: emitted method BODIES call pgmq.*
// functions, so runtime behavior is only proven against a database with
// the pgmq extension installed. Emission and shapes are tested; the
// repo's plain-Postgres harness cannot execute the extension.

export type PgmqTargetOptions = TargetOptions;

function clientName(queue: string): string {
  const clean = queue.replace(/[^a-zA-Z0-9_]/g, "_");
  return `${clean}Queue`;
}

export class PgmqTarget implements Target<PgmqTargetOptions> {
  readonly name = "pgmq";
  readonly fileExtension = ".mjs";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("pgmq is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: PgmqTargetOptions): SnapshotFile[] {
    const queues = snapshot.tables
      .filter((t) => t.schema === "pgmq" && t.name.startsWith("q_"))
      .map((t) => t.name.slice(2));

    const lines: string[] = ["// Generated by supawatch. Do not edit."];
    if (queues.length === 0) {
      lines.push(
        "// No pgmq queues detected. Queues appear as pgmq.q_<name> tables;",
        '// add "pgmq" to `schemas` in supawatch.config.ts on a database with',
        "// the pgmq extension installed.",
        "export const queues = {};",
        "",
      );
      return [{ file: "pgmq-clients.mjs", content: lines.join("\n") }];
    }

    for (const queue of queues) {
      const name = clientName(queue);
      // Queue names are generation-time constants; embed them as plain
      // SQL string literals in the emitted bodies.
      const qsql = "'" + queue.replace(/'/g, "''") + "'";
      lines.push(
        "",
        `export function ${name}(sql) {`,
        "  return {",
        "    async send(message, delaySeconds = 0) {",
        `      const rows = await sql.unsafe("select pgmq.send(${qsql}, $1::jsonb, $2::integer) as msg_id", [JSON.stringify(message), delaySeconds]);`,
        "      return rows[0].msg_id;",
        "    },",
        "    async read({ vt = 30, qty = 1 } = {}) {",
        `      return await sql.unsafe("select * from pgmq.read(${qsql}, $1::integer, $2::integer)", [vt, qty]);`,
        "    },",
        "    async pop() {",
        `      const rows = await sql.unsafe("select * from pgmq.pop(${qsql})");`,
        "      return rows[0] ?? null;",
        "    },",
        "    async archive(msgId) {",
        `      const rows = await sql.unsafe("select pgmq.archive(${qsql}, $1::bigint) as ok", [msgId]);`,
        "      return rows[0].ok === true;",
        "    },",
        "    async remove(msgId) {",
        `      const rows = await sql.unsafe("select pgmq.delete(${qsql}, $1::bigint) as ok", [msgId]);`,
        "      return rows[0].ok === true;",
        "    },",
        "  };",
        "}",
      );
    }
    lines.push(
      "",
      `export const queues = { ${queues.map((qname) => `${JSON.stringify(qname)}: ${clientName(qname)}`).join(", ")} };`,
      "",
    );
    return [{ file: "pgmq-clients.mjs", content: lines.join("\n") }];
  }
}

export default PgmqTarget;
