import type {
  Snapshot,
  SnapshotFile,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits pgtap tests, one SQL file per run, asserting the structure that
// actually exists: tables, columns with types and nullability, primary
// and foreign keys, RLS enablement, and the presence of every existing
// policy by name. Supabase's own docs call raw pgTAP inaccessible to
// most web developers; generated structure tests lower that wall and
// regenerate with the schema. Run them with supabase test db or pg_prove.

export type PgtapTargetOptions = TargetOptions;

function lit(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

export class PgtapTarget implements Target<PgtapTargetOptions> {
  readonly name = "pgtap";
  readonly fileExtension = ".sql";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("pgtap is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: PgtapTargetOptions): SnapshotFile[] {
    const tables = snapshot.tables.filter((t) => t.kind === "table");
    const assertions: string[] = [];

    for (const t of tables) {
      assertions.push(`select has_table(${lit(t.schema)}, ${lit(t.name)}, ${lit(`${t.name} exists`)});`);
      for (const col of t.columns) {
        assertions.push(
          `select has_column(${lit(t.schema)}, ${lit(t.name)}, ${lit(col.name)}, ${lit(`${t.name}.${col.name} exists`)});`,
        );
        assertions.push(
          col.nullable
            ? `select col_is_null(${lit(t.schema)}, ${lit(t.name)}, ${lit(col.name)}, ${lit(`${t.name}.${col.name} allows null`)});`
            : `select col_not_null(${lit(t.schema)}, ${lit(t.name)}, ${lit(col.name)}, ${lit(`${t.name}.${col.name} is not null`)});`,
        );
      }
      if (t.primaryKey.length > 0) {
        const cols = "array[" + t.primaryKey.map(lit).join(", ") + "]";
        assertions.push(
          `select col_is_pk(${lit(t.schema)}, ${lit(t.name)}, ${cols}, ${lit(`${t.name} primary key`)});`,
        );
      }
      for (const fk of t.foreignKeys) {
        const cols = "array[" + fk.columns.map(lit).join(", ") + "]";
        assertions.push(
          `select col_is_fk(${lit(t.schema)}, ${lit(t.name)}, ${cols}, ${lit(`${t.name} fk ${fk.name}`)});`,
        );
      }
      if (t.rlsEnabled) {
        // Core pgtap ships no rls_enabled (that is a Supabase test-helpers
        // function), so assert straight off pg_class: the suite then runs
        // under plain pg_prove and supabase test db alike.
        assertions.push(
          `select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = ${lit(t.schema)} and c.relname = ${lit(t.name)}), ${lit(`rls enabled on ${t.schema}.${t.name}`)});`,
        );
        for (const p of t.policies) {
          assertions.push(
            `select policies_are(${lit(t.schema)}, ${lit(t.name)}, array[${t.policies.map((x) => lit(x.name)).join(", ")}], ${lit(`${t.name} policies`)});`,
          );
          break; // policies_are asserts the full set once
        }
      }
    }

    const lines: string[] = [
      "-- Generated by supawatch. Do not edit.",
      "-- Run with supabase test db, or pg_prove against a database with pgtap installed.",
      "begin;",
      `select plan(${assertions.length});`,
      "",
      ...assertions,
      "",
      "select * from finish();",
      "rollback;",
      "",
    ];
    return [{ file: "structure.pgtap.sql", content: lines.join("\n") }];
  }
}

export default PgtapTarget;
