import type {
  RuntimeType,
  Snapshot,
  SnapshotFile,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits schema-dictionary.md: the data dictionary onboarding and
// compliance keep asking for and nobody maintains by hand. Column
// comments come from Postgres itself (comment on column ...), so the
// database stays the single source of documentation truth.

export type DictionaryTargetOptions = TargetOptions;

function runtimeLabel(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return runtime.integer ? "number (integer)" : "number";
    case "string":
      return runtime.format ? `string (${runtime.format})` : "string";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "bytes":
      return "Uint8Array";
    case "json":
      return "json (unknown shape)";
    case "unknown":
      return "unknown";
    case "array":
      return `array of ${runtimeLabel(runtime.element)}`;
    case "enum":
      return `enum: ${runtime.labels.join(", ")}`;
  }
}

export class DictionaryTarget implements Target<DictionaryTargetOptions> {
  readonly name = "dictionary";
  readonly fileExtension = ".md";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("dictionary is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: DictionaryTargetOptions): SnapshotFile[] {
    const lines: string[] = [
      "<!-- Generated by supawatch. Do not edit. -->",
      "# Data dictionary",
      "",
    ];

    for (const table of snapshot.tables) {
      const marker = table.kind === "view" ? " (view)" : "";
      lines.push(`## ${table.schema}.${table.name}${marker}`);
      if (table.comment) lines.push("", table.comment);
      lines.push(
        "",
        "| Column | SQL type | Runtime | Nullable | Notes |",
        "| --- | --- | --- | --- | --- |",
      );
      for (const col of table.columns) {
        const notes: string[] = [];
        if (table.primaryKey.includes(col.name)) notes.push("PK");
        const fk = table.foreignKeys.find((f) => f.columns.includes(col.name));
        if (fk) {
          notes.push(`FK to ${fk.referencedTable}.${fk.referencedColumns[0]}`);
        }
        if (col.identity) notes.push(`identity ${col.identity}`);
        if (col.generated) notes.push("generated");
        if (col.hasDefault) notes.push("has default");
        // comments land inside a markdown table cell: pipes and
        // newlines would break the row
        if (col.comment) notes.push(col.comment.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " "));
        lines.push(
          `| ${col.name} | ${col.sqlType} | ${runtimeLabel(col.runtime)} | ${col.nullable ? "yes" : "no"} | ${notes.join("; ")} |`,
        );
      }
      lines.push("");
    }

    if (snapshot.enums.length > 0) {
      lines.push("## Enums", "");
      for (const e of snapshot.enums) {
        lines.push(`- **${e.name}**: ${e.labels.join(", ")}`);
      }
      lines.push("");
    }
    if (snapshot.domains.length > 0) {
      lines.push("## Domains", "");
      for (const d of snapshot.domains) {
        lines.push(`- **${d.name}**: based on ${d.baseTypeName}`);
      }
      lines.push("");
    }
    if (snapshot.composites.length > 0) {
      lines.push("## Composite types", "");
      for (const c of snapshot.composites) {
        lines.push(
          `- **${c.name}**: ${c.fields.map((f) => `${f.name} ${f.pgTypeName}`).join(", ")}`,
        );
      }
      lines.push("");
    }

    return [{ file: "schema-dictionary.md", content: lines.join("\n") }];
  }
}

export default DictionaryTarget;
