import type {
  Column,
  Rendered,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";
import { exportBaseName, fileBaseName } from "@supawatch/core";

// Emits one field-config array per table for building forms: control kind,
// label, required flag, and options for enums, derived from the same
// insert semantics as the validator variants. Framework-agnostic data,
// pairs with any form library; the zod target's insert variant is the
// natural resolver next to it.

export type FormsTargetOptions = TargetOptions;

type ControlKind =
  | "text"
  | "number"
  | "checkbox"
  | "date"
  | "select"
  | "textarea";

function controlFor(col: Column): ControlKind {
  switch (col.runtime.kind) {
    case "number":
      return "number";
    case "boolean":
      return "checkbox";
    case "date":
      return "date";
    case "enum":
      return "select";
    case "json":
    case "unknown":
      return "textarea";
    default:
      return "text";
  }
}

function labelFor(name: string): string {
  const words = name.replace(/_/g, " ").trim();
  return words.charAt(0).toUpperCase() + words.slice(1);
}

function writableColumns(table: Table): Column[] {
  return table.columns.filter((c) => !c.generated && c.identity !== "always");
}

function insertOptional(col: Column): boolean {
  return col.hasDefault || col.nullable || col.identity === "default";
}

export function exportNameFor(table: Table, snapshot: Snapshot): string {
  return exportBaseName(table, snapshot) + "Fields";
}

export class FormsTarget implements Target<FormsTargetOptions> {
  readonly name = "forms";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(table: Table, snapshot: Snapshot, _opts: FormsTargetOptions): Rendered {
    const fields = writableColumns(table).map((col) => ({
      name: col.name,
      label: labelFor(col.name),
      control: controlFor(col),
      required: !insertOptional(col),
      ...(col.runtime.kind === "enum" ? { options: col.runtime.labels } : {}),
    }));
    return {
      imports: [],
      body: `export const ${exportNameFor(table, snapshot)} = ${JSON.stringify(fields, null, 2)};`,
      exportName: exportNameFor(table, snapshot),
    };
  }

  renderTypes(table: Table, snapshot: Snapshot, _opts: FormsTargetOptions): string {
    const name = exportNameFor(table, snapshot);
    return [
      "// Generated by supawatch. Do not edit.",
      "export type FieldConfig = {",
      "  name: string;",
      "  label: string;",
      '  control: "text" | "number" | "checkbox" | "date" | "select" | "textarea";',
      "  required: boolean;",
      "  options?: string[];",
      "};",
      `export declare const ${name}: FieldConfig[];`,
      "",
    ].join("\n");
  }
}

export default FormsTarget;
