import { pathToFileURL } from "node:url";
import { Value } from "@sinclair/typebox/value";
import type {
  Column,
  Rendered,
  RuntimeType,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
  Verdict,
  Verifier,
} from "@supawatch/core";
import type { TSchema } from "@sinclair/typebox";

export interface TypeboxTargetOptions extends TargetOptions {
  strict?: boolean;
}

// uuid stays a plain Type.String: TypeBox format validation needs a
// FormatRegistry the consumer would have to populate, and a schema that
// silently validates nothing is worse than one that says string.
function typeboxExpr(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return runtime.integer ? "Type.Integer()" : "Type.Number()";
    case "string":
      return "Type.String()";
    case "boolean":
      return "Type.Boolean()";
    case "date":
      return "Type.Date()";
    case "json":
    case "unknown":
      return "Type.Unknown()";
    case "enum": {
      const literals = runtime.labels
        .map((l) => `Type.Literal(${JSON.stringify(l)})`)
        .join(", ");
      return `Type.Union([${literals}])`;
    }
  }
}

function tsType(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "json":
    case "unknown":
      return "unknown";
    case "enum":
      return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
  }
}

export function exportNameFor(table: Table): string {
  return table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "Row";
}

function fieldSchema(col: Column): string {
  const base = typeboxExpr(col.runtime);
  if (col.nullable && col.runtime.kind !== "unknown" && col.runtime.kind !== "json") {
    return `Type.Union([${base}, Type.Null()])`;
  }
  return base;
}

export class TypeboxTarget implements Target<TypeboxTargetOptions> {
  readonly name = "typebox";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: true,
    brandedTypes: false,
    dateInstances: true,
  };

  renderTable(
    table: Table,
    _snapshot: Snapshot,
    opts: TypeboxTargetOptions,
  ): Rendered {
    const strict = opts.strict !== false;
    const fields = table.columns
      .map((col) => `  ${JSON.stringify(col.name)}: ${fieldSchema(col)},`)
      .join("\n");
    const tail = strict ? `, { additionalProperties: false }` : "";
    return {
      imports: [{ from: "@sinclair/typebox", names: ["Type"] }],
      body: `export const ${exportNameFor(table)} = Type.Object({\n${fields}\n}${tail});`,
      exportName: exportNameFor(table),
    };
  }

  renderTypes(table: Table, _snapshot: Snapshot, _opts: TypeboxTargetOptions): string {
    const name = exportNameFor(table);
    const rowType = table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "RowType";
    const fields = table.columns
      .map((col) => {
        const base = tsType(col.runtime);
        const t = col.nullable && base !== "unknown" ? `${base} | null` : base;
        return `  ${JSON.stringify(col.name)}: ${t};`;
      })
      .join("\n");
    return [
      "// Generated by supawatch. Do not edit.",
      'import type { TSchema } from "@sinclair/typebox";',
      "",
      `export type ${rowType} = {`,
      fields,
      "};",
      `export declare const ${name}: TSchema;`,
      "",
    ].join("\n");
  }

  verifier(): Verifier {
    return {
      async load(file: string, exportName: string): Promise<unknown> {
        const url = pathToFileURL(file).href + `?v=${Date.now()}`;
        const mod = (await import(url)) as Record<string, unknown>;
        const schema = mod[exportName];
        if (!schema) {
          throw new Error(
            `no export ${exportName} in ${file}; exports: ${Object.keys(mod).join(",")}`,
          );
        }
        return schema;
      },
      check(schema: unknown, value: unknown): Verdict {
        const s = schema as TSchema;
        if (Value.Check(s, value)) return { ok: true };
        const first = Value.Errors(s, value).First();
        return {
          ok: false,
          reason: first ? `${first.path}: ${first.message}` : "invalid",
        };
      },
    };
  }
}

export default TypeboxTarget;
