import type {
  Rendered,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";
import { exportBaseName, fileBaseName } from "@supawatch/core";

// Emits one typed repository per table over postgres.js: list, findById,
// create, update, remove. Reads validate through the generated Zod
// schemas, writes validate their inputs, and the identifier list is
// baked at generation time so nothing is interpolated from user input
// except through parameters.

export interface ServiceTargetOptions extends TargetOptions {
  schemasImportPath?: string;
}

function baseNameFor(table: Table, snapshot: Snapshot): string {
  return exportBaseName(table, snapshot);
}

export function exportNameFor(table: Table, snapshot: Snapshot): string {
  const base = baseNameFor(table, snapshot);
  return `create${base.charAt(0).toUpperCase() + base.slice(1)}Repo`;
}

function quotedIdent(table: Table): string {
  const q = (s: string) => '"' + s.replace(/"/g, '""') + '"';
  return `${q(table.schema)}.${q(table.name)}`;
}

export class ServiceTarget implements Target<ServiceTargetOptions> {
  readonly name = "service";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: true,
  };

  renderTable(table: Table, snapshot: Snapshot, opts: ServiceTargetOptions): Rendered {
    const base = baseNameFor(table, snapshot);
    const importPath = opts.schemasImportPath ?? "../zod";
    const rowName = `${base}Row`;
    const insertName = `${base}Insert`;
    const updateName = `${base}Update`;
    const ident = quotedIdent(table);
    const singlePk = table.primaryKey.length === 1 ? table.primaryKey[0] : null;
    const pkIdent = singlePk ? '"' + singlePk.replace(/"/g, '""') + '"' : null;

    const lines: string[] = [
      `export function ${exportNameFor(table, snapshot)}(sql) {`,
      "  return {",
      "    async list({ limit = 100, offset = 0 } = {}) {",
      `      const rows = await sql.unsafe('select * from ${ident} limit $1 offset $2', [Math.min(limit, 1000), offset]);`,
      `      return rows.map((row) => ${rowName}.parse(row));`,
      "    },",
    ];
    if (singlePk && pkIdent) {
      lines.push(
        "    async findById(id) {",
        `      const rows = await sql.unsafe('select * from ${ident} where ${pkIdent} = $1 limit 1', [id]);`,
        `      return rows.length > 0 ? ${rowName}.parse(rows[0]) : null;`,
        "    },",
      );
    }
    if (table.kind === "table") {
      lines.push(
        "    async create(input) {",
        `      const data = ${insertName}.parse(input);`,
        "      const keys = Object.keys(data);",
        `      const cols = keys.map((k) => '"' + k.replace(/"/g, '""') + '"').join(', ');`,
        "      const params = keys.map((_, i) => '$' + (i + 1)).join(', ');",
        `      const rows = await sql.unsafe('insert into ${ident} (' + cols + ') values (' + params + ') returning *', keys.map((k) => data[k]));`,
        `      return ${rowName}.parse(rows[0]);`,
        "    },",
      );
      if (singlePk && pkIdent) {
        lines.push(
          "    async update(id, patch) {",
          `      const data = ${updateName}.parse(patch);`,
          "      const keys = Object.keys(data);",
          "      if (keys.length === 0) return this.findById(id);",
          `      const sets = keys.map((k, i) => '"' + k.replace(/"/g, '""') + '" = $' + (i + 2)).join(', ');`,
          `      const rows = await sql.unsafe('update ${ident} set ' + sets + ' where ${pkIdent} = $1 returning *', [id, ...keys.map((k) => data[k])]);`,
          `      return rows.length > 0 ? ${rowName}.parse(rows[0]) : null;`,
          "    },",
          "    async remove(id) {",
          `      const rows = await sql.unsafe('delete from ${ident} where ${pkIdent} = $1 returning ${pkIdent}', [id]);`,
          "      return rows.length > 0;",
          "    },",
        );
      }
    }
    lines.push("  };", "}");

    const names =
      table.kind === "table"
        ? `${rowName}, ${insertName}, ${updateName}`
        : rowName;
    return {
      imports: [{ from: `${importPath}/${fileBaseName(table, snapshot)}.mjs`, names: [names] }],
      body: lines.join("\n"),
      exportName: exportNameFor(table, snapshot),
    };
  }

  renderTypes(table: Table, snapshot: Snapshot, _opts: ServiceTargetOptions): string {
    const name = exportNameFor(table, snapshot);
    return [
      "// Generated by supawatch. Do not edit.",
      "// Loosely typed on purpose: the generated zod .d.mts files carry",
      "// row and variant types; compose them at the call site as needed.",
      `export declare function ${name}(sql: { unsafe(text: string, params?: unknown[]): Promise<any[]> }): any;`,
      "",
    ].join("\n");
  }
}

export default ServiceTarget;
