import type {
  Snapshot,
  SnapshotFile,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits ai-tools.mjs: Vercel AI SDK tool() definitions per table, list
// and get, input schemas reused from the generated Zod target. Same
// audience as the MCP target, lighter integration: hand the returned
// object to generateText or streamText as `tools`.

export interface AiToolsTargetOptions extends TargetOptions {
  schemasImportPath?: string;
}

function baseNameFor(table: Table): string {
  return table.name.replace(/[^a-zA-Z0-9_]/g, "_");
}

function quotedIdent(table: Table): string {
  const q = (s: string) => '"' + s.replace(/"/g, '""') + '"';
  return `${q(table.schema)}.${q(table.name)}`;
}

export class AiToolsTarget implements Target<AiToolsTargetOptions> {
  readonly name = "ai-tools";
  readonly fileExtension = ".mjs";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("ai-tools is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, opts: AiToolsTargetOptions): SnapshotFile[] {
    const importPath = opts.schemasImportPath ?? "./zod";
    const tables = snapshot.tables.filter((t) => t.kind === "table");

    const lines: string[] = [
      "// Generated by supawatch. Do not edit.",
      'import { tool } from "ai";',
      'import { z } from "zod";',
    ];
    for (const table of tables) {
      lines.push(
        `import { ${baseNameFor(table)}Row } from ${JSON.stringify(`${importPath}/${table.name}.mjs`)};`,
      );
    }
    lines.push("", "export function createAiTools({ sql }) {", "  return {");
    for (const table of tables) {
      const base = baseNameFor(table);
      const ident = quotedIdent(table);
      lines.push(
        `    ${base}_list: tool({`,
        `      description: ${JSON.stringify(`List rows from ${table.schema}.${table.name}`)},`,
        "      inputSchema: z.object({ limit: z.number().int().min(1).max(100).optional() }),",
        "      execute: async ({ limit }) => {",
        `        const rows = await sql.unsafe('select * from ${ident} limit ' + Math.min(limit ?? 20, 100));`,
        `        return rows.map((row) => ${base}Row.parse(row));`,
        "      },",
        "    }),",
      );
      if (table.primaryKey.length === 1) {
        const pk = table.primaryKey[0];
        const pkIdent = '"' + pk.replace(/"/g, '""') + '"';
        lines.push(
          `    ${base}_get: tool({`,
          `      description: ${JSON.stringify(`Fetch one row from ${table.schema}.${table.name} by ${pk}`)},`,
          `      inputSchema: ${base}Row.pick({ ${JSON.stringify(pk)}: true }),`,
          "      execute: async (input) => {",
          `        const rows = await sql.unsafe('select * from ${ident} where ${pkIdent} = $1 limit 1', [input[${JSON.stringify(pk)}]]);`,
          `        return rows.length > 0 ? ${base}Row.parse(rows[0]) : null;`,
          "      },",
          "    }),",
        );
      }
    }
    lines.push("  };", "}", "");
    return [{ file: "ai-tools.mjs", content: lines.join("\n") }];
  }
}

export default AiToolsTarget;
