import {
  arrayRuntimeFor,
  runtimeFor,
  type Column,
  type RuntimeType,
  type Snapshot,
  type SnapshotFile,
  type Target,
  type TargetCapabilities,
  type TargetOptions,
} from "@supawatch/core";
import { exportBaseName, fileBaseName } from "@supawatch/core";

// Emits realtime.types.ts: per-table payload aliases for supabase-js
// realtime channels, closing the documented realtime-js gap where
// RealtimePostgresChangesPayload's own typing does not match the wire.
// Row shapes follow the MEASURED PostgREST JSON profile, because that is
// what realtime delivers over the socket. Types only; no runtime code.

export type RealtimeTargetOptions = TargetOptions;

function tsType(runtime: RuntimeType, snapshot: Snapshot): string {
  switch (runtime.kind) {
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "string";
    case "bytes":
      return "string";
    case "json":
    case "unknown":
      return "unknown";
    case "array": {
      const el = tsType(runtime.element, snapshot);
      return el.includes("|") ? `(${el})[]` : `${el}[]`;
    }
    case "enum":
      return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
  }
}

// Re-resolve each column under the supabase-js profile from its catalog
// identity, exactly like the Database bridge does.
function wireRuntime(col: Column, snapshot: Snapshot): RuntimeType {
  if (col.runtime.kind === "array") {
    return arrayRuntimeFor(col.runtime.element, 1, "supabase-js");
  }
  const kind = snapshot.enums.some((e) => e.name === col.pgTypeName)
    ? "e"
    : snapshot.composites.some((c) => c.name === col.pgTypeName)
      ? "c"
      : "b";
  return runtimeFor(col.pgTypeName, kind, { enums: snapshot.enums }, "supabase-js");
}

function baseNameFor(table: { schema: string; name: string }, snapshot: Snapshot): string {
  const clean = exportBaseName(table, snapshot);
  return clean.charAt(0).toUpperCase() + clean.slice(1);
}

export class RealtimeTarget implements Target<RealtimeTargetOptions> {
  readonly name = "realtime";
  readonly fileExtension = ".ts";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("realtime is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: RealtimeTargetOptions): SnapshotFile[] {
    const lines: string[] = [
      "// Generated by supawatch. Do not edit.",
      '// Wire shapes follow the measured PostgREST JSON profile: numeric and',
      "// int8 arrive as numbers, dates as strings, enum arrays as arrays.",
      'import type { RealtimePostgresChangesPayload } from "@supabase/supabase-js";',
      "",
    ];
    for (const table of snapshot.tables.filter((t) => t.kind === "table")) {
      const base = baseNameFor(table, snapshot);
      const fields = table.columns
        .map((col) => {
          const t = tsType(wireRuntime(col, snapshot), snapshot);
          const full = col.nullable && t !== "unknown" ? `${t} | null` : t;
          return `  ${JSON.stringify(col.name)}: ${full};`;
        })
        .join("\n");
      lines.push(
        `export type ${base}WireRow = {`,
        fields,
        "};",
        `export type ${base}Changes = RealtimePostgresChangesPayload<${base}WireRow>;`,
        "",
      );
    }
    return [{ file: "realtime.types.ts", content: lines.join("\n") }];
  }
}

export default RealtimeTarget;
