import type {
  Column,
  Rendered,
  RuntimeType,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits one fast-check Arbitrary per table producing rows shaped exactly
// like driver output, so property tests fuzz the same values the schemas
// validate. The repo's own suite asserts that every generated arbitrary
// satisfies the generated Zod schema for the same table.

export type FastCheckTargetOptions = TargetOptions;

function arbExpr(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return runtime.integer
        ? "fc.integer()"
        : "fc.double({ noNaN: true, noDefaultInfinity: true })";
    case "string":
      switch (runtime.format) {
        case "uuid":
          return "fc.uuid()";
        case "numeric":
          // decimal string with two places, like the driver's numeric
          return 'fc.integer({ min: -99999999, max: 99999999 }).map((n) => (n / 100).toFixed(2))';
        case "bigint":
          return "fc.bigInt().map((v) => v.toString())";
        default:
          return "fc.string()";
      }
    case "boolean":
      return "fc.boolean()";
    case "date":
      return "fc.date({ noInvalidDate: true })";
    case "bytes":
      return "fc.uint8Array()";
    case "json":
      return "fc.jsonValue()";
    case "unknown":
      return "fc.anything()";
    case "array":
      return `fc.array(${arbExpr(runtime.element)}, { maxLength: 5 })`;
    case "enum": {
      const labels = runtime.labels.map((l) => JSON.stringify(l)).join(", ");
      return `fc.constantFrom(${labels})`;
    }
  }
}

function tsType(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "bytes":
      return "Uint8Array";
    case "json":
    case "unknown":
      return "unknown";
    case "array": {
      const el = tsType(runtime.element);
      return el.includes("|") ? `(${el})[]` : `${el}[]`;
    }
    case "enum":
      return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
  }
}

export function exportNameFor(table: Table): string {
  return table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "Arb";
}

function fieldArb(col: Column): string {
  const base = arbExpr(col.runtime);
  return col.nullable ? `fc.option(${base}, { nil: null })` : base;
}

export class FastCheckTarget implements Target<FastCheckTargetOptions> {
  readonly name = "fast-check";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: true,
  };

  renderTable(table: Table, _snapshot: Snapshot, _opts: FastCheckTargetOptions): Rendered {
    const fields = table.columns
      .map((col) => `  ${JSON.stringify(col.name)}: ${fieldArb(col)},`)
      .join("\n");
    return {
      imports: [{ from: "fast-check", namespace: "fc" }],
      body: `export const ${exportNameFor(table)} = fc.record({\n${fields}\n});`,
      exportName: exportNameFor(table),
    };
  }

  renderTypes(table: Table, _snapshot: Snapshot, _opts: FastCheckTargetOptions): string {
    const name = exportNameFor(table);
    const rowType = table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "ArbRow";
    const fields = table.columns
      .map((col) => {
        const base = tsType(col.runtime);
        const t = col.nullable && base !== "unknown" ? `${base} | null` : base;
        return `  ${JSON.stringify(col.name)}: ${t};`;
      })
      .join("\n");
    return [
      "// Generated by supawatch. Do not edit.",
      'import type { Arbitrary } from "fast-check";',
      "",
      `export type ${rowType} = {`,
      fields,
      "};",
      `export declare const ${name}: Arbitrary<${rowType}>;`,
      "",
    ].join("\n");
  }
}

export default FastCheckTarget;
