#!/usr/bin/env python3
"""Build every shipped supawatch asset from the one source in brand.py."""
import os
import subprocess
from brand import (INK, PAPER, MONO600, MONO500, MONO400, SANS400, SANS600,
                   Face, mark, lockup, arrow, svg_open)

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(REPO, "assets")
os.makedirs(OUT, exist_ok=True)

# The target list is read out of the CLI rather than retyped, so a banner
# can never quietly disagree with what the tool actually accepts.
CONFIG = os.path.join(REPO, "packages/cli/src/config.ts")


def target_kinds():
    src = open(CONFIG).read()
    start = src.index("export const TARGET_KINDS")
    end = src.index("] as const", start)
    body = src[start:end]
    kinds = []
    for line in body.splitlines()[1:]:
        line = line.strip()
        if line.startswith('"'):
            kinds.append(line.split('"')[1])
    if not kinds:
        raise SystemExit("parsed no target kinds; refusing to build a wrong banner")
    return kinds


TARGETS = target_kinds()

# The product thesis in three rows: the SQL type chart on the left, what
# the driver hands your code on the right. This is the whole reason the
# tool exists, so it earns the space on both banners.
ROWS = [
    ("int8",        "z.string()"),
    ("numeric",     "z.string()"),
    ("timestamptz", "z.instanceof(Date)"),
]


def panel(P, x, y, label_size=11, row_size=17, gap=36, colw=132, arrow_w=26,
          rule_w=430):
    """The mapping datasheet."""
    m5, m4 = Face.get(MONO500), Face.get(MONO400)
    o = []
    a, _ = m5.paths("POSTGRES SAYS", x, y, label_size, P["dim"], tracking=0.10)
    o.append(a)
    b, _ = m5.paths("YOUR CODE RECEIVES", x + colw + arrow_w + 22, y,
                    label_size, P["dim"], tracking=0.10)
    o.append(b)
    o.append(f'<path d="M{x} {y + 14} L{x + rule_w} {y + 14}" '
             f'stroke="{P["rule2"]}" stroke-width="1"/>')
    for i, (lhs, rhs) in enumerate(ROWS):
        ry = y + gap + i * gap
        t, _ = m4.paths(lhs, x, ry, row_size, P["mut"])
        o.append(t)
        o.append(arrow(x + colw, ry - row_size * 0.30, arrow_w, P["dim"]))
        t2, _ = m5.paths(rhs, x + colw + arrow_w + 22, ry, row_size, P["signal"])
        o.append(t2)
    return "".join(o)


# ------------------------------------------------------------------ banner
def banner(P, w=1280, h=340):
    s4 = Face.get(SANS400)
    m4 = Face.get(MONO400)
    o = [svg_open(w, h, P["bg"])]

    lk, lw, lh = lockup(72, 80, 62, P["fg"], P["signal"])
    o.append(lk)

    t, _ = s4.paths("Your Postgres schema, compiled to everything.",
                    72, 200, 21, P["fg"])
    o.append(t)
    t2, _ = m4.paths("Regenerated by the database itself.", 72, 232, 14, P["mut"])
    o.append(t2)
    t3, _ = m4.paths("Verified against real rows.", 72, 252, 14, P["mut"])
    o.append(t3)

    # hairline splitting the claim from the evidence for it
    o.append(f'<path d="M712 80 L712 256" stroke="{P["rule"]}" stroke-width="1"/>')
    o.append(panel(P, 760, 112, gap=36))

    # Baseline rule with a signal segment measured to the lockup, so the
    # accent marks something real rather than decorating a corner.
    o.append(f'<path d="M72 290 L{w - 72} 290" stroke="{P["rule"]}" '
             f'stroke-width="1"/>')
    o.append(f'<path d="M72 290 L{72 + lw:.2f} 290" stroke="{P["signal"]}" '
             f'stroke-width="1.5"/>')
    o.append("</svg>")
    return "\n".join(o)


# ---------------------------------------------------------- social preview
def target_index(P, x, y, width, cols=3, size=14, lh=20):
    """Every target kind, set as a dense index.

    The claim on the card is "compiled to everything"; printing the actual
    list is what makes that checkable instead of merely asserted.
    """
    m4, m5 = Face.get(MONO400), Face.get(MONO500)
    o = []
    head, _ = m5.paths(f"{len(TARGETS)} GENERATION TARGETS", x, y, 12,
                       P["dim"], tracking=0.10)
    o.append(head)
    o.append(f'<path d="M{x} {y + 14} L{x + width} {y + 14}" '
             f'stroke="{P["rule2"]}" stroke-width="1"/>')
    colw = width / cols
    rows = -(-len(TARGETS) // cols)          # ceil
    for i, k in enumerate(TARGETS):
        cx = x + (i // rows) * colw
        cy = y + 40 + (i % rows) * lh
        t, _ = m4.paths(k, cx, cy, size, P["mut"])
        o.append(t)
    return "".join(o), 40 + rows * lh


def social(P, w=1280, h=640):
    s4 = Face.get(SANS400)
    m4 = Face.get(MONO400)
    o = [svg_open(w, h, P["bg"])]

    lk, lw, lh = lockup(88, 108, 76, P["fg"], P["signal"])
    o.append(lk)

    t, _ = s4.paths("Your Postgres schema, compiled to everything.",
                    88, 254, 27, P["fg"])
    o.append(t)
    t2, _ = m4.paths("Regenerated by the database itself. Verified against real rows.",
                     88, 288, 15, P["mut"])
    o.append(t2)

    o.append(f'<path d="M88 326 L{w - 88} 326" stroke="{P["rule"]}" stroke-width="1"/>')

    # left: the evidence.  right: the scale. Both columns are sized to
    # bottom out together, and each header rule spans its own column so
    # the two halves read as one datasheet rather than two leftovers.
    o.append(panel(P, 88, 362, label_size=12, row_size=18, gap=40,
                   colw=140, arrow_w=28, rule_w=round(lw)))
    idx, _ = target_index(P, 680, 362, w - 88 - 680, cols=4, size=13, lh=20)
    o.append(idx)

    # the other half of the story: what the watcher prints when a schema moves
    t3, _ = m4.paths("[supawatch] public.tasks gained blocked_reason",
                     88, 556, 14, P["dim"])
    o.append(t3)
    t4, _ = m4.paths("[supawatch] ground-truth check, tasks: 3/3 passed",
                     88, 576, 14, P["dim"])
    o.append(t4)

    o.append(f'<path d="M88 {h - 44} L{w - 88} {h - 44}" stroke="{P["rule"]}" '
             f'stroke-width="1"/>')
    o.append(f'<path d="M88 {h - 44} L{88 + lw:.2f} {h - 44}" '
             f'stroke="{P["signal"]}" stroke-width="1.5"/>')
    o.append("</svg>")
    return "\n".join(o)


# ------------------------------------------------------- marks and wordmarks
def logomark(P, size=48, mono=False, bg=None):
    o = [svg_open(size, size, bg)]
    o.append(mark(0, 0, size, P["fg"], P["signal"], mono=mono))
    o.append("</svg>")
    return "\n".join(o)


def wordmark(P, size=48, pad=16, mono=False, bg=None):
    body, w, h = lockup(pad, pad, size, P["fg"], P["signal"], mono=mono)
    o = [svg_open(round(w + pad * 2), round(h + pad * 2), bg), body, "</svg>"]
    return "\n".join(o)


def write(name, content):
    p = os.path.join(OUT, name)
    with open(p, "w") as f:
        f.write(content)
    return p


built = []
built.append(write("banner-dark.svg", banner(INK)))
built.append(write("banner-light.svg", banner(PAPER)))
built.append(write("social-preview.svg", social(INK)))
built.append(write("logomark.svg", logomark(INK, 48)))
built.append(write("logomark-light.svg", logomark(PAPER, 48)))
built.append(write("logomark-mono-dark.svg", logomark(INK, 48, mono=True)))
built.append(write("logomark-mono-light.svg", logomark(PAPER, 48, mono=True)))
built.append(write("wordmark-dark.svg", wordmark(INK, 48)))
built.append(write("wordmark-light.svg", wordmark(PAPER, 48)))

# Raster deliverables. GitHub's social preview field takes an image file,
# not an SVG, and app icons need real pixels at fixed sizes.
subprocess.run(["rsvg-convert", "-w", "1280", "-h", "640",
                os.path.join(OUT, "social-preview.svg"),
                "-o", os.path.join(OUT, "social-preview.png")], check=True)
built.append(os.path.join(OUT, "social-preview.png"))

# PNG banners at 2x, as a fallback for anywhere that will not take an SVG
for name in ("banner-dark", "banner-light"):
    p = os.path.join(OUT, f"{name}.png")
    subprocess.run(["rsvg-convert", "-w", "2560", "-h", "680",
                    os.path.join(OUT, f"{name}.svg"), "-o", p], check=True)
    built.append(p)

# icon PNGs come off an opaque tile so they never sit on a host background
for s in (512, 256, 128, 64, 32, 16):
    tmp = f"/tmp/icon-{s}.svg"
    with open(tmp, "w") as f:
        f.write(logomark(INK, 48, bg=INK["bg"]))
    p = os.path.join(OUT, f"icon-{s}.png")
    subprocess.run(["rsvg-convert", "-w", str(s), "-h", str(s), tmp, "-o", p],
                   check=True)
    built.append(p)

# favicon.ico, every frame drawn at its own size rather than resampled from
# one large raster: a 16px bracket turns to mush when it is downscaled.
from PIL import Image  # noqa: E402  (only needed for the .ico)

ICO = [16, 24, 32, 48, 64, 128, 256]
frames = []
for s in ICO:
    src = f"/tmp/sw-fav-{s}.svg"
    with open(src, "w") as f:
        f.write(logomark(INK, 48, bg=INK["bg"]))
    png = f"/tmp/sw-fav-{s}.png"
    subprocess.run(["rsvg-convert", "-w", str(s), "-h", str(s), src, "-o", png],
                   check=True)
    frames.append(Image.open(png).convert("RGBA"))

ico_path = os.path.join(OUT, "favicon.ico")
frames[-1].save(ico_path, format="ICO", sizes=[(s, s) for s in ICO],
                append_images=frames[:-1])
with Image.open(ico_path) as ico:
    for s in ICO:
        ico.size = (s, s)
        ico.load()            # raises if a frame did not survive the write
built.append(ico_path)

for p in built:
    print(f"  {os.path.getsize(p):>8}  {p}")
print(f"\n{len(built)} assets, {len(TARGETS)} target kinds read from config.ts")
