import type {
  Rendered,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";
import { exportBaseName, fileBaseName } from "@supawatch/core";

// Emits one tRPC router factory per table: list, byId, and create
// procedures whose inputs are the ALREADY-GENERATED Zod schemas from the
// zod target. Nothing here invents validation; it wires the validated
// pieces to a postgres.js connection.
//
// Requirements, stated up front rather than discovered at runtime:
// - the zod target must run in the same config, with emit.insert enabled
//   (create imports the Insert variant),
// - the emitted factory takes the consumer's own initTRPC instance and
//   postgres.js connection; this package has no runtime dependencies.

export interface TrpcTargetOptions extends TargetOptions {
  // Relative import path from this target's outDir to the zod target's.
  schemasImportPath?: string;
}

function baseNameFor(table: Table, snapshot: Snapshot): string {
  return exportBaseName(table, snapshot);
}

export function exportNameFor(table: Table, snapshot: Snapshot): string {
  const base = baseNameFor(table, snapshot);
  return `create${base.charAt(0).toUpperCase() + base.slice(1)}Router`;
}

function quotedIdent(table: Table): string {
  const q = (s: string) => '"' + s.replace(/"/g, '""') + '"';
  return `${q(table.schema)}.${q(table.name)}`;
}

export class TrpcTarget implements Target<TrpcTargetOptions> {
  readonly name = "trpc";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: true,
  };

  renderTable(table: Table, snapshot: Snapshot, opts: TrpcTargetOptions): Rendered {
    const base = baseNameFor(table, snapshot);
    const importPath = opts.schemasImportPath ?? "../zod";
    const rowName = `${base}Row`;
    const insertName = `${base}Insert`;
    const ident = quotedIdent(table);
    const singlePk = table.primaryKey.length === 1 ? table.primaryKey[0] : null;

    const lines: string[] = [
      `export function ${exportNameFor(table, snapshot)}(t, sql) {`,
      "  return t.router({",
      "    list: t.procedure.query(async () => {",
      `      const rows = await sql.unsafe('select * from ${ident} limit 100');`,
      `      return rows.map((row) => ${rowName}.parse(row));`,
      "    }),",
    ];
    if (singlePk) {
      const pkIdent = '"' + singlePk.replace(/"/g, '""') + '"';
      lines.push(
        `    byId: t.procedure.input(${rowName}.pick({ ${JSON.stringify(singlePk)}: true })).query(async ({ input }) => {`,
        `      const rows = await sql.unsafe('select * from ${ident} where ${pkIdent} = $1 limit 1', [input[${JSON.stringify(singlePk)}]]);`,
        `      return rows.length > 0 ? ${rowName}.parse(rows[0]) : null;`,
        "    }),",
      );
    }
    if (table.kind === "table") {
      lines.push(
        `    create: t.procedure.input(${insertName}).mutation(async ({ input }) => {`,
        "      const keys = Object.keys(input);",
        `      const cols = keys.map((k) => '"' + k.replace(/"/g, '""') + '"').join(', ');`,
        "      const params = keys.map((_, i) => '$' + (i + 1)).join(', ');",
        `      const rows = await sql.unsafe('insert into ${ident} (' + cols + ') values (' + params + ') returning *', keys.map((k) => input[k]));`,
        `      return ${rowName}.parse(rows[0]);`,
        "    }),",
      );
    }
    lines.push("  });", "}");

    const importNames =
      table.kind === "table" ? `${rowName}, ${insertName}` : rowName;
    return {
      imports: [
        { from: `${importPath}/${fileBaseName(table, snapshot)}.mjs`, names: [importNames] },
      ],
      body: lines.join("\n"),
      exportName: exportNameFor(table, snapshot),
    };
  }

  renderTypes(table: Table, snapshot: Snapshot, _opts: TrpcTargetOptions): string {
    const name = exportNameFor(table, snapshot);
    return [
      "// Generated by supawatch. Do not edit.",
      "// Loosely typed on purpose: the consumer's initTRPC instance and",
      "// postgres.js connection carry the real types at the call site.",
      `export declare function ${name}(t: any, sql: { unsafe(text: string, params?: unknown[]): Promise<any[]> }): any;`,
      "",
    ].join("\n");
  }
}

export default TrpcTarget;
