import type {
  Snapshot,
  SnapshotFile,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";
import { exportBaseName, isMultiSchema } from "@supawatch/core";

// Emits schema.erd.md: a Mermaid erDiagram inside a fenced block, which
// GitHub renders natively. Regenerated on every schema change, so the
// diagram is correct forever instead of correct once.
//
// Mermaid's grammar only accepts word-safe tokens for entity and
// attribute names, and database identifiers are free-form ("Order Log",
// "users; drop table users--", unicode). Entities therefore use a safe
// identifier with the real name as a quoted display alias, and
// attributes sanitize their tokens, keeping the real column name in the
// attribute comment. Verified by actually parsing the output with
// mermaid in the repo's suite.

export type ErdTargetOptions = TargetOptions;

// Mermaid tokens must not start with a digit or a hyphen.
const WORD_SAFE = /^[A-Za-z_][A-Za-z0-9_-]*$/;

function safeToken(s: string): string {
  const t = s.replace(/[^A-Za-z0-9_-]/g, "_");
  const led = /^[0-9]/.test(t) ? `_${t}` : t;
  return led === "" ? "_" : led;
}

// Mermaid quoted strings cannot carry a double quote.
function quotable(s: string): string {
  return s.replace(/"/g, "'").replace(/[\n\r\t]/g, " ");
}

function attrLines(table: Table): string[] {
  const used = new Map<string, number>();
  return table.columns.map((col) => {
    const markers: string[] = [];
    if (table.primaryKey.includes(col.name)) markers.push("PK");
    if (table.foreignKeys.some((fk) => fk.columns.includes(col.name))) {
      markers.push("FK");
    }
    const marker = markers.length > 0 ? ` ${markers.join(",")}` : "";
    const type = safeToken(col.pgTypeName);
    let name = WORD_SAFE.test(col.name) ? col.name : safeToken(col.name);
    // sanitized names can collide inside one entity ("a b" and "a-b")
    const n = used.get(name) ?? 0;
    used.set(name, n + 1);
    if (n > 0) name = `${name}_${n + 1}`;
    const comment =
      name === col.name ? "" : ` "column: ${quotable(col.name)}"`;
    return `    ${type} ${name}${marker}${comment}`;
  });
}

export class ErdTarget implements Target<ErdTargetOptions> {
  readonly name = "erd";
  readonly fileExtension = ".md";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("erd is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: ErdTargetOptions): SnapshotFile[] {
    const multi = isMultiSchema(snapshot);
    const identFor = (t: Table): string => exportBaseName(t, snapshot);
    const displayFor = (t: Table): string =>
      multi ? `${t.schema}.${t.name}` : t.name;

    const lines: string[] = [
      "<!-- Generated by supawatch. Do not edit. -->",
      "```mermaid",
      "erDiagram",
    ];

    for (const table of snapshot.tables) {
      // A nullable FK column means the relationship itself is optional.
      for (const fk of table.foreignKeys) {
        const optional = fk.columns.every((c) => {
          const col = table.columns.find((x) => x.name === c);
          return col?.nullable === true;
        });
        const cardinality = optional ? "}o--o|" : "}o--||";
        // Resolve the parent by schema AND name: two schemas can hold
        // same-named tables, and a bare name would wire the wrong one.
        const parent = snapshot.tables.find(
          (x) => x.schema === fk.referencedSchema && x.name === fk.referencedTable,
        );
        const parentIdent = parent ? identFor(parent) : safeToken(fk.referencedTable);
        lines.push(
          `  ${identFor(table)} ${cardinality} ${parentIdent} : "${quotable(fk.name)}"`,
        );
      }
    }

    for (const table of snapshot.tables) {
      const ident = identFor(table);
      const display = displayFor(table);
      const header =
        ident === display
          ? `  ${ident} {`
          : `  ${ident}["${quotable(display)}"] {`;
      lines.push(header);
      lines.push(...attrLines(table));
      lines.push("  }");
    }

    lines.push("```", "");
    return [{ file: "schema.erd.md", content: lines.join("\n") }];
  }
}

export default ErdTarget;
