import type {
  Snapshot,
  SnapshotFile,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits schema.erd.md: a Mermaid erDiagram inside a fenced block, which
// GitHub renders natively. Regenerated on every schema change, so the
// diagram is correct forever instead of correct once.

export type ErdTargetOptions = TargetOptions;

function attrLines(table: Table): string[] {
  return table.columns.map((col) => {
    const markers: string[] = [];
    if (table.primaryKey.includes(col.name)) markers.push("PK");
    if (table.foreignKeys.some((fk) => fk.columns.includes(col.name))) {
      markers.push("FK");
    }
    // Mermaid attribute types must be single tokens; pgTypeName is one.
    const marker = markers.length > 0 ? ` ${markers.join(",")}` : "";
    return `    ${col.pgTypeName} ${col.name}${marker}`;
  });
}

export class ErdTarget implements Target<ErdTargetOptions> {
  readonly name = "erd";
  readonly fileExtension = ".md";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("erd is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: ErdTargetOptions): SnapshotFile[] {
    const lines: string[] = [
      "<!-- Generated by supawatch. Do not edit. -->",
      "```mermaid",
      "erDiagram",
    ];

    for (const table of snapshot.tables) {
      // A nullable FK column means the relationship itself is optional.
      for (const fk of table.foreignKeys) {
        const optional = fk.columns.every((c) => {
          const col = table.columns.find((x) => x.name === c);
          return col?.nullable === true;
        });
        const cardinality = optional ? "}o--o|" : "}o--||";
        lines.push(
          `  ${table.name} ${cardinality} ${fk.referencedTable} : "${fk.name}"`,
        );
      }
    }

    for (const table of snapshot.tables) {
      lines.push(`  ${table.name} {`);
      lines.push(...attrLines(table));
      lines.push("  }");
    }

    lines.push("```", "");
    return [{ file: "schema.erd.md", content: lines.join("\n") }];
  }
}

export default ErdTarget;
