import {
  arrayRuntimeFor,
  runtimeFor,
  type Column,
  type RuntimeType,
  type Snapshot,
  type SnapshotFile,
  type Table,
  type Target,
  type TargetCapabilities,
  type TargetOptions,
} from "@supawatch/core";

// Emits a Database interface compatible with supabase-js generics, so
// generated schemas and supabase-js share one source of truth. Types
// follow the MEASURED PostgREST JSON profile regardless of the config
// profile, because that is what supabase-js actually receives.

export type SupabaseTypesOptions = TargetOptions;

function tsType(runtime: RuntimeType, jsonRef: string): string {
  switch (runtime.kind) {
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "string"; // never reached under the supabase-js profile; defensive
    case "bytes":
      return "string";
    case "json":
      return jsonRef;
    case "unknown":
      return "unknown";
    case "array": {
      const el = tsType(runtime.element, jsonRef);
      return el.includes("|") ? `(${el})[]` : `${el}[]`;
    }
    case "enum":
      return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
  }
}

// Re-resolve a column's runtime under the supabase-js profile from its
// catalog identity, so the bridge is correct even when the rest of the
// run uses the postgres-js profile.
function bridgeRuntime(col: Column, snapshot: Snapshot): RuntimeType {
  if (col.runtime.kind === "array") {
    return arrayRuntimeFor(
      runtimeFromName(col.runtime.element, snapshot),
      1,
      "supabase-js",
    );
  }
  return runtimeFor(col.pgTypeName, kindOf(col, snapshot), { enums: snapshot.enums }, "supabase-js");
}

function kindOf(col: Column, snapshot: Snapshot): string {
  if (snapshot.enums.some((e) => e.name === col.pgTypeName)) return "e";
  if (snapshot.composites.some((c) => c.name === col.pgTypeName)) return "c";
  return "b";
}

function runtimeFromName(element: RuntimeType, _snapshot: Snapshot): RuntimeType {
  return element;
}

// Database identifiers are free-form ("Order Log", "café", "select");
// quote any key that is not a plain TS identifier.
function tsKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function writableColumns(table: Table): Column[] {
  return table.columns.filter((c) => !c.generated && c.identity !== "always");
}

function insertOptional(col: Column): boolean {
  return col.hasDefault || col.nullable || col.identity === "default";
}

function fieldLine(
  col: Column,
  snapshot: Snapshot,
  optional: boolean,
  indent: string,
): string {
  const runtime = bridgeRuntime(col, snapshot);
  let t = tsType(runtime, "Json");
  if (col.nullable && t !== "unknown") t = `${t} | null`;
  return `${indent}${tsKey(col.name)}${optional ? "?" : ""}: ${t}`;
}

export class SupabaseTypesTarget implements Target<SupabaseTypesOptions> {
  readonly name = "supabase-types";
  readonly fileExtension = ".ts";
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("supabase-types is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: SupabaseTypesOptions): SnapshotFile[] {
    const schemas = [...new Set(snapshot.tables.map((t) => t.schema))].sort();
    const lines: string[] = [
      "// Generated by supawatch. Do not edit.",
      "export type Json =",
      "  | string",
      "  | number",
      "  | boolean",
      "  | null",
      "  | { [key: string]: Json | undefined }",
      "  | Json[];",
      "",
      "export interface Database {",
    ];

    for (const schema of schemas) {
      const tables = snapshot.tables.filter(
        (t) => t.schema === schema && t.kind === "table",
      );
      const views = snapshot.tables.filter(
        (t) => t.schema === schema && t.kind === "view",
      );
      const enums = snapshot.enums.filter((e) => e.schema === schema);
      const composites = snapshot.composites.filter((c) => c.schema === schema);

      lines.push(`  ${tsKey(schema)}: {`);

      lines.push("    Tables: {");
      for (const table of tables) {
        lines.push(`      ${tsKey(table.name)}: {`);
        lines.push("        Row: {");
        for (const col of table.columns) {
          lines.push(fieldLine(col, snapshot, false, "          ") + ";");
        }
        lines.push("        };");
        lines.push("        Insert: {");
        for (const col of writableColumns(table)) {
          lines.push(
            fieldLine(col, snapshot, insertOptional(col), "          ") + ";",
          );
        }
        lines.push("        };");
        lines.push("        Update: {");
        for (const col of writableColumns(table)) {
          lines.push(fieldLine(col, snapshot, true, "          ") + ";");
        }
        lines.push("        };");
        lines.push("        Relationships: [");
        for (const fk of table.foreignKeys) {
          lines.push("          {");
          lines.push(`            foreignKeyName: ${JSON.stringify(fk.name)};`);
          lines.push(
            `            columns: [${fk.columns.map((c) => JSON.stringify(c)).join(", ")}];`,
          );
          lines.push("            isOneToOne: false;");
          lines.push(
            `            referencedRelation: ${JSON.stringify(fk.referencedTable)};`,
          );
          lines.push(
            `            referencedColumns: [${fk.referencedColumns.map((c) => JSON.stringify(c)).join(", ")}];`,
          );
          lines.push("          },");
        }
        lines.push("        ];");
        lines.push("      };");
      }
      lines.push("    };");

      lines.push("    Views: {");
      for (const view of views) {
        lines.push(`      ${tsKey(view.name)}: {`);
        lines.push("        Row: {");
        for (const col of view.columns) {
          lines.push(fieldLine(col, snapshot, false, "          ") + ";");
        }
        lines.push("        };");
        lines.push("      };");
      }
      lines.push("    };");

      const fns = snapshot.functions.filter((f) => f.schema === schema);
      if (fns.length === 0) {
        lines.push("    Functions: Record<string, never>;");
      } else {
        lines.push("    Functions: {");
        // Overloaded names share one key: Args and Returns become unions
        // of the signatures, never duplicate keys (invalid TS).
        const byName = new Map<string, typeof fns>();
        for (const fn of fns) {
          const group = byName.get(fn.name) ?? [];
          group.push(fn);
          byName.set(fn.name, group);
        }
        for (const [name, group] of byName) {
          const argShapes = group.map((fn) => {
            if (fn.args.length === 0) return "Record<string, never>";
            const fields = fn.args.map((arg) => {
              const t = tsType(
                runtimeFor(arg.pgTypeName, "b", { enums: snapshot.enums }, "supabase-js"),
                "Json",
              );
              return `${tsKey(arg.name)}${arg.hasDefault ? "?" : ""}: ${t}`;
            });
            return `{ ${fields.join("; ")} }`;
          });
          const returnShapes = [
            ...new Set(
              group.map((fn) => {
                const ret = tsType(
                  runtimeFor(fn.returns.pgTypeName, "b", { enums: snapshot.enums }, "supabase-js"),
                  "Json",
                );
                return fn.returns.isSet ? `(${ret})[]` : ret;
              }),
            ),
          ];
          lines.push(`      ${tsKey(name)}: {`);
          lines.push(`        Args: ${[...new Set(argShapes)].join(" | ")};`);
          lines.push(`        Returns: ${returnShapes.join(" | ")};`);
          lines.push("      };");
        }
        lines.push("    };");
      }

      lines.push("    Enums: {");
      for (const e of enums) {
        lines.push(
          `      ${tsKey(e.name)}: ${e.labels.map((l) => JSON.stringify(l)).join(" | ")};`,
        );
      }
      lines.push("    };");

      lines.push("    CompositeTypes: {");
      for (const c of composites) {
        lines.push(`      ${tsKey(c.name)}: {`);
        for (const f of c.fields) {
          const t = tsType(f.runtime, "Json");
          lines.push(`        ${tsKey(f.name)}: ${t} | null;`);
        }
        lines.push("      };");
      }
      lines.push("    };");

      lines.push("  };");
    }

    lines.push("}");
    lines.push("");
    return [{ file: "database.types.ts", content: lines.join("\n") }];
  }
}

export default SupabaseTypesTarget;
