import {
  arrayRuntimeFor,
  runtimeFor,
  type Column,
  type RuntimeType,
  type Snapshot,
  type SnapshotFile,
  type Table,
  type Target,
  type TargetCapabilities,
  type TargetOptions,
} from "@supawatch/core";

// Emits a Database interface compatible with supabase-js generics, so
// generated schemas and supabase-js share one source of truth. Types
// follow the MEASURED PostgREST JSON profile regardless of the config
// profile, because that is what supabase-js actually receives.

export type SupabaseTypesOptions = TargetOptions;

function tsType(runtime: RuntimeType, jsonRef: string): string {
  switch (runtime.kind) {
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "string"; // never reached under the supabase-js profile; defensive
    case "bytes":
      return "string";
    case "json":
      return jsonRef;
    case "unknown":
      return "unknown";
    case "array": {
      const el = tsType(runtime.element, jsonRef);
      return el.includes("|") ? `(${el})[]` : `${el}[]`;
    }
    case "enum":
      return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
  }
}

// Re-resolve a column's runtime under the supabase-js profile from its
// catalog identity, so the bridge is correct even when the rest of the
// run uses the postgres-js profile.
function bridgeRuntime(col: Column, snapshot: Snapshot): RuntimeType {
  if (col.runtime.kind === "array") {
    return arrayRuntimeFor(
      runtimeFromName(col.runtime.element, snapshot),
      1,
      "supabase-js",
    );
  }
  if (col.runtime.kind === "string" && col.runtime.format === "array-literal") {
    // postgres-js collapses enum arrays to a raw literal; PostgREST
    // parses them. Recover the element labels via the enum reference.
    const e = snapshot.enums.find((x) => x.name === col.enumRef);
    if (e) {
      return { kind: "array", element: { kind: "enum", labels: e.labels } };
    }
  }
  return runtimeFor(col.pgTypeName, kindOf(col, snapshot), { enums: snapshot.enums }, "supabase-js");
}

function kindOf(col: Column, snapshot: Snapshot): string {
  if (snapshot.enums.some((e) => e.name === col.pgTypeName)) return "e";
  if (snapshot.composites.some((c) => c.name === col.pgTypeName)) return "c";
  return "b";
}

function runtimeFromName(element: RuntimeType, _snapshot: Snapshot): RuntimeType {
  return element;
}

function writableColumns(table: Table): Column[] {
  return table.columns.filter((c) => !c.generated && c.identity !== "always");
}

function insertOptional(col: Column): boolean {
  return col.hasDefault || col.nullable || col.identity === "default";
}

function fieldLine(
  col: Column,
  snapshot: Snapshot,
  optional: boolean,
  indent: string,
): string {
  const runtime = bridgeRuntime(col, snapshot);
  let t = tsType(runtime, "Json");
  if (col.nullable && t !== "unknown") t = `${t} | null`;
  return `${indent}${col.name}${optional ? "?" : ""}: ${t}`;
}

export class SupabaseTypesTarget implements Target<SupabaseTypesOptions> {
  readonly name = "supabase-types";
  readonly fileExtension = ".ts";
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("supabase-types is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: SupabaseTypesOptions): SnapshotFile[] {
    const schemas = [...new Set(snapshot.tables.map((t) => t.schema))].sort();
    const lines: string[] = [
      "// Generated by supawatch. Do not edit.",
      "export type Json =",
      "  | string",
      "  | number",
      "  | boolean",
      "  | null",
      "  | { [key: string]: Json | undefined }",
      "  | Json[];",
      "",
      "export interface Database {",
    ];

    for (const schema of schemas) {
      const tables = snapshot.tables.filter(
        (t) => t.schema === schema && t.kind === "table",
      );
      const views = snapshot.tables.filter(
        (t) => t.schema === schema && t.kind === "view",
      );
      const enums = snapshot.enums.filter((e) => e.schema === schema);
      const composites = snapshot.composites.filter((c) => c.schema === schema);

      lines.push(`  ${schema}: {`);

      lines.push("    Tables: {");
      for (const table of tables) {
        lines.push(`      ${table.name}: {`);
        lines.push("        Row: {");
        for (const col of table.columns) {
          lines.push(fieldLine(col, snapshot, false, "          ") + ";");
        }
        lines.push("        };");
        lines.push("        Insert: {");
        for (const col of writableColumns(table)) {
          lines.push(
            fieldLine(col, snapshot, insertOptional(col), "          ") + ";",
          );
        }
        lines.push("        };");
        lines.push("        Update: {");
        for (const col of writableColumns(table)) {
          lines.push(fieldLine(col, snapshot, true, "          ") + ";");
        }
        lines.push("        };");
        lines.push("        Relationships: [");
        for (const fk of table.foreignKeys) {
          lines.push("          {");
          lines.push(`            foreignKeyName: ${JSON.stringify(fk.name)};`);
          lines.push(
            `            columns: [${fk.columns.map((c) => JSON.stringify(c)).join(", ")}];`,
          );
          lines.push("            isOneToOne: false;");
          lines.push(
            `            referencedRelation: ${JSON.stringify(fk.referencedTable)};`,
          );
          lines.push(
            `            referencedColumns: [${fk.referencedColumns.map((c) => JSON.stringify(c)).join(", ")}];`,
          );
          lines.push("          },");
        }
        lines.push("        ];");
        lines.push("      };");
      }
      lines.push("    };");

      lines.push("    Views: {");
      for (const view of views) {
        lines.push(`      ${view.name}: {`);
        lines.push("        Row: {");
        for (const col of view.columns) {
          lines.push(fieldLine(col, snapshot, false, "          ") + ";");
        }
        lines.push("        };");
        lines.push("      };");
      }
      lines.push("    };");

      lines.push("    Functions: Record<string, never>;");

      lines.push("    Enums: {");
      for (const e of enums) {
        lines.push(
          `      ${e.name}: ${e.labels.map((l) => JSON.stringify(l)).join(" | ")};`,
        );
      }
      lines.push("    };");

      lines.push("    CompositeTypes: {");
      for (const c of composites) {
        lines.push(`      ${c.name}: {`);
        for (const f of c.fields) {
          const t = tsType(f.runtime, "Json");
          lines.push(`        ${f.name}: ${t} | null;`);
        }
        lines.push("      };");
      }
      lines.push("    };");

      lines.push("  };");
    }

    lines.push("}");
    lines.push("");
    return [{ file: "database.types.ts", content: lines.join("\n") }];
  }
}

export default SupabaseTypesTarget;
