import { mkdir, readdir, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Rendered } from "./types.js";

// Generators write through a sink, never through fs directly. The default
// sink writes atomically (temp file then rename) because a concurrent
// reader of a plain truncate-and-write sees an empty module; that failure
// was observed, not imagined. A dry-run or check sink swaps in here.
export interface FileSink {
  write(file: string, content: string): Promise<void>;
  prune(dir: string, keep: Set<string>, extension: string): Promise<string[]>;
}

// Each write gets its OWN temp name. A fixed `<file>.tmp` collides when
// two supawatch processes run at once (a watcher plus a manual
// generate, two CI jobs): one renames the shared temp away and the
// other's rename fails with ENOENT, killing that run. Unique names let
// both finish, with the last rename winning and the target never torn.
let writeCounter = 0;

export const atomicSink: FileSink = {
  async write(file, content) {
    await mkdir(path.dirname(file), { recursive: true });
    const tmp = `${file}.${process.pid}.${writeCounter++}.tmp`;
    try {
      await writeFile(tmp, content);
      await rename(tmp, file);
    } catch (err) {
      await unlink(tmp).catch(() => {});
      throw err;
    }
  },
  async prune(dir, keep, extension) {
    const removed: string[] = [];
    let entries: string[];
    try {
      entries = await readdir(dir);
    } catch {
      return removed;
    }
    for (const entry of entries) {
      if (entry.endsWith(extension) && !keep.has(entry)) {
        await unlink(path.join(dir, entry));
        removed.push(entry);
      }
    }
    return removed;
  },
};

export function assemble(rendered: Rendered): string {
  const header = "// Generated by supawatch. Do not edit.";
  const imports = rendered.imports
    .map((i) => {
      if (i.namespace) {
        return `import * as ${i.namespace} from ${JSON.stringify(i.from)};`;
      }
      return `import { ${(i.names ?? []).join(", ")} } from ${JSON.stringify(i.from)};`;
    })
    .join("\n");
  return [header, imports, "", rendered.body, ""].join("\n");
}
