import { mkdir, readdir, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Rendered } from "./types.js";

// Generators write through a sink, never through fs directly. The default
// sink writes atomically (temp file then rename) because a concurrent
// reader of a plain truncate-and-write sees an empty module; that failure
// was observed, not imagined. A dry-run or check sink swaps in here.
export interface FileSink {
  write(file: string, content: string): Promise<void>;
  prune(dir: string, keep: Set<string>, extension: string): Promise<string[]>;
}

export const atomicSink: FileSink = {
  async write(file, content) {
    await mkdir(path.dirname(file), { recursive: true });
    const tmp = `${file}.tmp`;
    await writeFile(tmp, content);
    await rename(tmp, file);
  },
  async prune(dir, keep, extension) {
    const removed: string[] = [];
    let entries: string[];
    try {
      entries = await readdir(dir);
    } catch {
      return removed;
    }
    for (const entry of entries) {
      if (entry.endsWith(extension) && !keep.has(entry)) {
        await unlink(path.join(dir, entry));
        removed.push(entry);
      }
    }
    return removed;
  },
};

export function assemble(rendered: Rendered): string {
  const header = "// Generated by supawatch. Do not edit.";
  const imports = rendered.imports
    .map((i) => `import { ${i.names.join(", ")} } from ${JSON.stringify(i.from)};`)
    .join("\n");
  return [header, imports, "", rendered.body, ""].join("\n");
}
