import type {
  Rendered,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";
import { exportBaseName, fileBaseName } from "@supawatch/core";

// Emits one oRPC router factory per table on the same plan as the tRPC
// target: list, byId, create, inputs validated by the generated Zod
// schemas. API verified empirically against @orpc/server 1.15 (os
// builder, input().handler(), os.router, call) before writing this.

export interface OrpcTargetOptions extends TargetOptions {
  schemasImportPath?: string;
}

function baseNameFor(table: Table, snapshot: Snapshot): string {
  return exportBaseName(table, snapshot);
}

export function exportNameFor(table: Table, snapshot: Snapshot): string {
  const base = baseNameFor(table, snapshot);
  return `create${base.charAt(0).toUpperCase() + base.slice(1)}Orpc`;
}

function quotedIdent(table: Table): string {
  const q = (s: string) => '"' + s.replace(/"/g, '""') + '"';
  return `${q(table.schema)}.${q(table.name)}`;
}

export class OrpcTarget implements Target<OrpcTargetOptions> {
  readonly name = "orpc";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: true,
  };

  renderTable(table: Table, snapshot: Snapshot, opts: OrpcTargetOptions): Rendered {
    const base = baseNameFor(table, snapshot);
    const importPath = opts.schemasImportPath ?? "../zod";
    const rowName = `${base}Row`;
    const insertName = `${base}Insert`;
    const ident = quotedIdent(table);
    const singlePk = table.primaryKey.length === 1 ? table.primaryKey[0] : null;

    const lines: string[] = [
      `export function ${exportNameFor(table, snapshot)}(sql) {`,
      "  const procedures = {",
      "    list: os.handler(async () => {",
      `      const rows = await sql.unsafe('select * from ${ident} limit 100');`,
      `      return rows.map((row) => ${rowName}.parse(row));`,
      "    }),",
    ];
    if (singlePk) {
      const pkIdent = '"' + singlePk.replace(/"/g, '""') + '"';
      lines.push(
        `    byId: os.input(${rowName}.pick({ ${JSON.stringify(singlePk)}: true })).handler(async ({ input }) => {`,
        `      const rows = await sql.unsafe('select * from ${ident} where ${pkIdent} = $1 limit 1', [input[${JSON.stringify(singlePk)}]]);`,
        `      return rows.length > 0 ? ${rowName}.parse(rows[0]) : null;`,
        "    }),",
      );
    }
    if (table.kind === "table") {
      lines.push(
        `    create: os.input(${insertName}).handler(async ({ input }) => {`,
        "      const keys = Object.keys(input);",
        `      const cols = keys.map((k) => '"' + k.replace(/"/g, '""') + '"').join(', ');`,
        "      const params = keys.map((_, i) => '$' + (i + 1)).join(', ');",
        `      const rows = await sql.unsafe('insert into ${ident} (' + cols + ') values (' + params + ') returning *', keys.map((k) => input[k]));`,
        `      return ${rowName}.parse(rows[0]);`,
        "    }),",
      );
    }
    lines.push("  };", "  return os.router(procedures);", "}");

    const names = table.kind === "table" ? `${rowName}, ${insertName}` : rowName;
    return {
      imports: [
        { from: "@orpc/server", names: ["os"] },
        { from: `${importPath}/${fileBaseName(table, snapshot)}.mjs`, names: [names] },
      ],
      body: lines.join("\n"),
      exportName: exportNameFor(table, snapshot),
    };
  }

  renderTypes(table: Table, snapshot: Snapshot, _opts: OrpcTargetOptions): string {
    const name = exportNameFor(table, snapshot);
    return [
      "// Generated by supawatch. Do not edit.",
      `export declare function ${name}(sql: { unsafe(text: string, params?: unknown[]): Promise<any[]> }): any;`,
      "",
    ].join("\n");
  }
}

export default OrpcTarget;
