import { pathToFileURL } from "node:url";
import { type } from "arktype";
import type {
  Column,
  Rendered,
  RuntimeType,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
  Verdict,
  Verifier,
} from "@supawatch/core";

export interface ArktypeTargetOptions extends TargetOptions {
  strict?: boolean;
}

// ArkType has two languages: the string DSL for field values, and Type
// expressions. A field value may be either, but the two must never be
// concatenated. Most kinds render as DSL strings; bytes renders as a
// type.instanceOf expression, because the DSL keyword 'Uint8Array'
// throws at parse time. The tagged return keeps the two apart.
type ArkField =
  | { lang: "dsl"; code: string }
  | { lang: "expr"; code: string };

function arkExpr(runtime: RuntimeType): ArkField {
  switch (runtime.kind) {
    case "number":
      return { lang: "dsl", code: runtime.integer ? "number.integer" : "number" };
    case "string":
      return {
        lang: "dsl",
        code: runtime.format === "uuid" ? "string.uuid" : "string",
      };
    case "boolean":
      return { lang: "dsl", code: "boolean" };
    case "date":
      return { lang: "dsl", code: "Date" };
    case "bytes":
      return { lang: "expr", code: "type.instanceOf(Uint8Array)" };
    case "json":
    case "unknown":
      return { lang: "dsl", code: "unknown" };
    case "array": {
      const el = arkExpr(runtime.element);
      if (el.lang === "expr") return { lang: "expr", code: `${el.code}.array()` };
      const needsParens = el.code.includes("|");
      return {
        lang: "dsl",
        code: needsParens ? `(${el.code})[]` : `${el.code}[]`,
      };
    }
    case "enum":
      return {
        lang: "dsl",
        code: runtime.labels.map((l) => `'${l.replace(/'/g, "\\'")}'`).join("|"),
      };
  }
}

function tsType(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "bytes":
      return "Uint8Array";
    case "json":
    case "unknown":
      return "unknown";
    case "array": {
      const el = tsType(runtime.element);
      return el.includes("|") ? `(${el})[]` : `${el}[]`;
    }
    case "enum":
      return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
  }
}

export function exportNameFor(table: Table): string {
  return table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "Row";
}

// Returns the literal code for the field value: quoted DSL, or a raw
// Type expression. Nullability composes inside each language.
function fieldSchema(col: Column): string {
  const base = arkExpr(col.runtime);
  const nullable =
    col.nullable && col.runtime.kind !== "unknown" && col.runtime.kind !== "json";
  if (base.lang === "expr") {
    return nullable ? `${base.code}.or("null")` : base.code;
  }
  const dsl = nullable ? `${base.code}|null` : base.code;
  return JSON.stringify(dsl);
}

export class ArktypeTarget implements Target<ArktypeTargetOptions> {
  readonly name = "arktype";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: true,
    brandedTypes: false,
    dateInstances: true,
  };

  renderTable(
    table: Table,
    _snapshot: Snapshot,
    opts: ArktypeTargetOptions,
  ): Rendered {
    const strict = opts.strict !== false;
    const fields = table.columns
      .map((col) => `  ${JSON.stringify(col.name)}: ${fieldSchema(col)},`)
      .join("\n");
    const rejectLine = strict ? `  "+": "reject",\n` : "";
    return {
      imports: [{ from: "arktype", names: ["type"] }],
      body: `export const ${exportNameFor(table)} = type({\n${rejectLine}${fields}\n});`,
      exportName: exportNameFor(table),
    };
  }

  renderTypes(table: Table, _snapshot: Snapshot, _opts: ArktypeTargetOptions): string {
    const name = exportNameFor(table);
    const rowType = table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "RowType";
    const fields = table.columns
      .map((col) => {
        const base = tsType(col.runtime);
        const t = col.nullable && base !== "unknown" ? `${base} | null` : base;
        return `  ${JSON.stringify(col.name)}: ${t};`;
      })
      .join("\n");
    return [
      "// Generated by supawatch. Do not edit.",
      'import type { Type } from "arktype";',
      "",
      `export type ${rowType} = {`,
      fields,
      "};",
      `export declare const ${name}: Type<${rowType}>;`,
      "",
    ].join("\n");
  }

  verifier(): Verifier {
    return {
      async load(file: string, exportName: string): Promise<unknown> {
        const url = pathToFileURL(file).href + `?v=${Date.now()}`;
        const mod = (await import(url)) as Record<string, unknown>;
        const schema = mod[exportName];
        if (!schema) {
          throw new Error(
            `no export ${exportName} in ${file}; exports: ${Object.keys(mod).join(",")}`,
          );
        }
        return schema;
      },
      check(schema: unknown, value: unknown): Verdict {
        const out = (schema as (v: unknown) => unknown)(value);
        if (out instanceof type.errors) {
          return { ok: false, reason: out.summary };
        }
        return { ok: true };
      },
    };
  }
}

export default ArktypeTarget;
