import { pathToFileURL } from "node:url";
import { type } from "arktype";
import type {
  Column,
  Rendered,
  RuntimeType,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
  Verdict,
  Verifier,
} from "@supawatch/core";

export interface ArktypeTargetOptions extends TargetOptions {
  strict?: boolean;
}

// ArkType's field DSL is a string language; expressions below are always
// full field-position strings, never mixed with Type-object combinators,
// because the two are different languages and mixing them is a syntax
// error in emitted code.
function arkExpr(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return runtime.integer ? "number.integer" : "number";
    case "string":
      return runtime.format === "uuid" ? "string.uuid" : "string";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "json":
    case "unknown":
      return "unknown";
    case "enum":
      return runtime.labels.map((l) => `'${l.replace(/'/g, "\\'")}'`).join("|");
  }
}

function tsType(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "json":
    case "unknown":
      return "unknown";
    case "enum":
      return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
  }
}

export function exportNameFor(table: Table): string {
  return table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "Row";
}

function fieldSchema(col: Column): string {
  const base = arkExpr(col.runtime);
  // unknown already includes null.
  if (col.nullable && col.runtime.kind !== "unknown" && col.runtime.kind !== "json") {
    return `${base}|null`;
  }
  return base;
}

export class ArktypeTarget implements Target<ArktypeTargetOptions> {
  readonly name = "arktype";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: true,
    brandedTypes: false,
    dateInstances: true,
  };

  renderTable(
    table: Table,
    _snapshot: Snapshot,
    opts: ArktypeTargetOptions,
  ): Rendered {
    const strict = opts.strict !== false;
    const fields = table.columns
      .map((col) => `  ${JSON.stringify(col.name)}: ${JSON.stringify(fieldSchema(col))},`)
      .join("\n");
    const rejectLine = strict ? `  "+": "reject",\n` : "";
    return {
      imports: [{ from: "arktype", names: ["type"] }],
      body: `export const ${exportNameFor(table)} = type({\n${rejectLine}${fields}\n});`,
      exportName: exportNameFor(table),
    };
  }

  renderTypes(table: Table, _snapshot: Snapshot, _opts: ArktypeTargetOptions): string {
    const name = exportNameFor(table);
    const rowType = table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "RowType";
    const fields = table.columns
      .map((col) => {
        const base = tsType(col.runtime);
        const t = col.nullable && base !== "unknown" ? `${base} | null` : base;
        return `  ${JSON.stringify(col.name)}: ${t};`;
      })
      .join("\n");
    return [
      "// Generated by supawatch. Do not edit.",
      'import type { Type } from "arktype";',
      "",
      `export type ${rowType} = {`,
      fields,
      "};",
      `export declare const ${name}: Type<${rowType}>;`,
      "",
    ].join("\n");
  }

  verifier(): Verifier {
    return {
      async load(file: string, exportName: string): Promise<unknown> {
        const url = pathToFileURL(file).href + `?v=${Date.now()}`;
        const mod = (await import(url)) as Record<string, unknown>;
        const schema = mod[exportName];
        if (!schema) {
          throw new Error(
            `no export ${exportName} in ${file}; exports: ${Object.keys(mod).join(",")}`,
          );
        }
        return schema;
      },
      check(schema: unknown, value: unknown): Verdict {
        const out = (schema as (v: unknown) => unknown)(value);
        if (out instanceof type.errors) {
          return { ok: false, reason: out.summary };
        }
        return { ok: true };
      },
    };
  }
}

export default ArktypeTarget;
