import { defineConfig } from "../packages/cli/dist/index.js";

export default defineConfig({
  schemas: ["public", "aux", "😱"],
  outDir: "./generated",
  source: { kind: "manual" },
  targets: [
    { kind: "zod", strict: true, emit: { insert: true, update: true } },
    { kind: "valibot", strict: true },
    { kind: "arktype", strict: true },
    { kind: "typebox", strict: true },
    { kind: "effect", strict: true },
    { kind: "json-schema", strict: true },
    { kind: "supabase-types" },
    { kind: "fast-check" },
    { kind: "factories" },
    { kind: "forms" },
    { kind: "trpc" },
    { kind: "orpc" },
    { kind: "rest" },
    { kind: "service" },
    { kind: "graphql" },
    { kind: "mcp" },
    { kind: "ai-tools" },
    { kind: "realtime" },
    { kind: "seed", rows: 2 },
    { kind: "pgtap" },
    { kind: "rls" },
    { kind: "pgmq" },
    { kind: "erd" },
    { kind: "dictionary" },
    { kind: "schema-card" },
    { kind: "schema-lock" },
  ],
});
