import type {
  Column,
  Rendered,
  RuntimeType,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits one typed fixture factory per table: makeTasks(overrides) returns
// a full, deterministic row in driver shape. Every generated factory row
// must satisfy the generated Zod schema for the same table; the repo's
// suite enforces exactly that, so a factory can never produce the narrow,
// wrong fixtures that hide bugs.

export type FactoriesTargetOptions = TargetOptions;

function defaultExpr(runtime: RuntimeType, seedPath: string): string {
  switch (runtime.kind) {
    case "number":
      return runtime.integer ? "1" : "1.5";
    case "string":
      switch (runtime.format) {
        case "uuid":
          // A real v4 literal: zod's z.uuid() enforces RFC 4122 version
          // and variant bits, so an all-zeros-style value is rejected.
          // The cross-check against the zod target caught exactly that.
          return '"9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"';
        case "numeric":
          return '"0.00"';
        case "bigint":
          return '"1"';
        default:
          return JSON.stringify(seedPath);
      }
    case "boolean":
      return "false";
    case "date":
      return "new Date(0)";
    case "bytes":
      return "new Uint8Array()";
    case "json":
    case "unknown":
      return "null";
    case "array":
      return "[]";
    case "enum":
      return JSON.stringify(runtime.labels[0] ?? "");
  }
}

function baseNameFor(table: Table): string {
  return table.name.replace(/[^a-zA-Z0-9_]/g, "_");
}

export function exportNameFor(table: Table): string {
  const base = baseNameFor(table);
  return "make" + base.charAt(0).toUpperCase() + base.slice(1);
}

function fieldDefault(table: Table, col: Column): string {
  if (col.nullable) return "null";
  return defaultExpr(col.runtime, `${table.name}.${col.name}`);
}

export class FactoriesTarget implements Target<FactoriesTargetOptions> {
  readonly name = "factories";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: true,
  };

  renderTable(table: Table, _snapshot: Snapshot, _opts: FactoriesTargetOptions): Rendered {
    const fields = table.columns
      .map((col) => `    ${JSON.stringify(col.name)}: ${fieldDefault(table, col)},`)
      .join("\n");
    const body = [
      `export function ${exportNameFor(table)}(overrides = {}) {`,
      "  return {",
      fields,
      "    ...overrides,",
      "  };",
      "}",
    ].join("\n");
    return { imports: [], body, exportName: exportNameFor(table) };
  }

  renderTypes(table: Table, _snapshot: Snapshot, _opts: FactoriesTargetOptions): string {
    const name = exportNameFor(table);
    const base = baseNameFor(table);
    const rowType = `${base}FactoryRow`;
    const tsType = (runtime: RuntimeType): string => {
      switch (runtime.kind) {
        case "number":
          return "number";
        case "string":
          return "string";
        case "boolean":
          return "boolean";
        case "date":
          return "Date";
        case "bytes":
          return "Uint8Array";
        case "json":
        case "unknown":
          return "unknown";
        case "array": {
          const el = tsType(runtime.element);
          return el.includes("|") ? `(${el})[]` : `${el}[]`;
        }
        case "enum":
          return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
      }
    };
    const fields = table.columns
      .map((col) => {
        const base = tsType(col.runtime);
        const t = col.nullable && base !== "unknown" ? `${base} | null` : base;
        return `  ${JSON.stringify(col.name)}: ${t};`;
      })
      .join("\n");
    return [
      "// Generated by supawatch. Do not edit.",
      `export type ${rowType} = {`,
      fields,
      "};",
      `export declare function ${name}(overrides?: Partial<${rowType}>): ${rowType};`,
      "",
    ].join("\n");
  }
}

export default FactoriesTarget;
