import type {
  Column,
  RuntimeType,
  Snapshot,
  SnapshotFile,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits schema-card.md: a compact, token-lean schema summary meant to be
// pasted into system prompts and agent context. Teams paste stale schema
// dumps today; this one is small and regenerates on every change.

export type SchemaCardTargetOptions = TargetOptions;

function shortType(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return runtime.integer ? "int" : "float";
    case "string":
      return runtime.format ?? "text";
    case "boolean":
      return "bool";
    case "date":
      return "date";
    case "bytes":
      return "bytes";
    case "json":
      return "json";
    case "unknown":
      return "?";
    case "array":
      return `${shortType(runtime.element)}[]`;
    case "enum":
      return `enum(${runtime.labels.join("|")})`;
  }
}

// Both date and timestamptz arrive as Date at runtime, but an LLM
// reading "date" plans calendar arithmetic; keep the SQL granularity.
function compactTemporal(sqlType: string): string {
  if (sqlType === "timestamp with time zone") return "timestamptz";
  if (sqlType === "timestamp without time zone") return "timestamp";
  return sqlType;
}

function columnToken(table: Table, col: Column): string {
  const fk = table.foreignKeys.find((f) => f.columns.includes(col.name));
  const parts: string[] = [col.name];
  if (table.primaryKey.includes(col.name)) parts.push("PK");
  if (fk) parts.push(`-> ${fk.referencedTable}.${fk.referencedColumns[0]}`);
  else if (col.runtime.kind === "date") parts.push(compactTemporal(col.sqlType));
  else parts.push(shortType(col.runtime));
  if (col.nullable) parts.push("null?");
  return parts.join(" ");
}

export class SchemaCardTarget implements Target<SchemaCardTargetOptions> {
  readonly name = "schema-card";
  readonly fileExtension = ".md";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("schema-card is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: SchemaCardTargetOptions): SnapshotFile[] {
    const lines: string[] = [
      "<!-- Generated by supawatch. Do not edit. -->",
      "# Database schema",
      "",
    ];
    for (const table of snapshot.tables) {
      const marker = table.kind === "view" ? " (view)" : "";
      const comment = table.comment ? ` : ${table.comment}` : "";
      lines.push(`- ${table.name}${marker}${comment}`);
      lines.push(
        `  ${table.columns.map((c) => columnToken(table, c)).join("; ")}`,
      );
    }
    if (snapshot.enums.length > 0) {
      lines.push("");
      for (const e of snapshot.enums) {
        lines.push(`- enum ${e.name}: ${e.labels.join(" | ")}`);
      }
    }
    lines.push("");
    return [{ file: "schema-card.md", content: lines.join("\n") }];
  }
}

export default SchemaCardTarget;
