import { readFileSync } from "node:fs";
import { Ajv } from "ajv";
import type {
  Column,
  Rendered,
  RuntimeType,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
  Verdict,
  Verifier,
} from "@supawatch/core";
import { exportBaseName, fileBaseName } from "@supawatch/core";

// Emits one JSON Schema (draft-07, the maximum-interop dialect) per
// table, describing the row as
// the DRIVER returns it, and carries an Ajv verifier so ground truth
// applies to these files like any validator target.

export type JsonSchemaTargetOptions = TargetOptions;

// JSON Schema has no type for JS Date instances or Uint8Array; those
// columns get an accept-anything schema with a $comment saying why. The
// honest alternative would be claiming "string", which would reject every
// real driver row and fail ground truth.
function schemaFor(runtime: RuntimeType): Record<string, unknown> {
  switch (runtime.kind) {
    case "number":
      return runtime.integer ? { type: "integer" } : { type: "number" };
    case "string":
      return { type: "string" };
    case "boolean":
      return { type: "boolean" };
    case "date":
      return { $comment: "JS Date instance at runtime; not expressible in JSON Schema" };
    case "bytes":
      return { $comment: "Uint8Array at runtime; not expressible in JSON Schema" };
    case "json":
    case "unknown":
      return {};
    case "array":
      return { type: "array", items: schemaFor(runtime.element) };
    case "enum":
      return { enum: runtime.labels };
  }
}

function fieldSchema(col: Column): Record<string, unknown> {
  const base = schemaFor(col.runtime);
  if (!col.nullable) return base;
  if (Object.keys(base).length === 0 || !("type" in base) && !("enum" in base)) {
    return base; // accept-anything already includes null
  }
  return { anyOf: [base, { type: "null" }] };
}

export function exportNameFor(table: Table, snapshot: Snapshot): string {
  return exportBaseName(table, snapshot) + "Row";
}

export class JsonSchemaTarget implements Target<JsonSchemaTargetOptions> {
  readonly name = "json-schema";
  readonly fileExtension = ".schema.json";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: true,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(table: Table, snapshot: Snapshot, opts: JsonSchemaTargetOptions): Rendered {
    const strict = opts.strict !== false;
    const properties: Record<string, unknown> = {};
    for (const col of table.columns) {
      properties[col.name] = fieldSchema(col);
    }
    const schema = {
      $schema: "http://json-schema.org/draft-07/schema#",
      $id: `${table.schema}.${table.name}`,
      $comment: "Generated by supawatch. Do not edit. Shapes follow driver runtime values.",
      type: "object",
      properties,
      required: table.columns.map((c) => c.name),
      additionalProperties: !strict,
    };
    return {
      imports: [],
      body: JSON.stringify(schema, null, 2) + "\n",
      exportName: exportNameFor(table, snapshot),
    };
  }

  assembleFile(rendered: Rendered): string {
    return rendered.body;
  }

  verifier(): Verifier {
    const ajv = new Ajv({ strict: false, allowUnionTypes: true });
    return {
      async load(file: string, _exportName: string): Promise<unknown> {
        const schema = JSON.parse(readFileSync(file, "utf8"));
        return ajv.compile(schema);
      },
      check(schema: unknown, value: unknown): Verdict {
        const validate = schema as {
          (v: unknown): boolean;
          errors?: { instancePath: string; message?: string }[] | null;
        };
        if (validate(value)) return { ok: true };
        const first = validate.errors?.[0];
        return {
          ok: false,
          reason: first ? `${first.instancePath} ${first.message ?? ""}`.trim() : "invalid",
        };
      },
    };
  }
}

export default JsonSchemaTarget;
