import type {
  Rendered,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";
import { exportBaseName, fileBaseName } from "@supawatch/core";

// Emits one Hono route module per table: GET list, GET by id, POST
// create, validated by the ALREADY-generated Zod schemas. The factory
// takes the consumer's postgres.js connection and returns a Hono app to
// mount wherever they like, including a Supabase Edge Function body.

export interface RestTargetOptions extends TargetOptions {
  schemasImportPath?: string;
}

function baseNameFor(table: Table, snapshot: Snapshot): string {
  return exportBaseName(table, snapshot);
}

export function exportNameFor(table: Table, snapshot: Snapshot): string {
  const base = baseNameFor(table, snapshot);
  return `create${base.charAt(0).toUpperCase() + base.slice(1)}Routes`;
}

function quotedIdent(table: Table): string {
  const q = (s: string) => '"' + s.replace(/"/g, '""') + '"';
  return `${q(table.schema)}.${q(table.name)}`;
}

export class RestTarget implements Target<RestTargetOptions> {
  readonly name = "rest";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: true,
  };

  renderTable(table: Table, snapshot: Snapshot, opts: RestTargetOptions): Rendered {
    const base = baseNameFor(table, snapshot);
    const importPath = opts.schemasImportPath ?? "../zod";
    const rowName = `${base}Row`;
    const insertName = `${base}Insert`;
    const ident = quotedIdent(table);
    const singlePk = table.primaryKey.length === 1 ? table.primaryKey[0] : null;

    const lines: string[] = [
      `export function ${exportNameFor(table, snapshot)}(sql) {`,
      "  const app = new Hono();",
      '  app.get("/", async (c) => {',
      `    const rows = await sql.unsafe('select * from ${ident} limit 100');`,
      `    return c.json(rows.map((row) => ${rowName}.parse(row)));`,
      "  });",
    ];
    if (singlePk) {
      const pkIdent = '"' + singlePk.replace(/"/g, '""') + '"';
      lines.push(
        '  app.get("/:id", async (c) => {',
        `    const rows = await sql.unsafe('select * from ${ident} where ${pkIdent} = $1 limit 1', [c.req.param("id")]);`,
        '    if (rows.length === 0) return c.json({ error: "not found" }, 404);',
        `    return c.json(${rowName}.parse(rows[0]));`,
        "  });",
      );
    }
    if (table.kind === "table") {
      lines.push(
        '  app.post("/", async (c) => {',
        "    const body = await c.req.json();",
        `    const parsed = ${insertName}.safeParse(body);`,
        "    if (!parsed.success) {",
        "      return c.json({ error: parsed.error.issues[0]?.message ?? \"invalid\" }, 400);",
        "    }",
        "    const keys = Object.keys(parsed.data);",
        `    const cols = keys.map((k) => '"' + k.replace(/"/g, '""') + '"').join(', ');`,
        "    const params = keys.map((_, i) => '$' + (i + 1)).join(', ');",
        `    const rows = await sql.unsafe('insert into ${ident} (' + cols + ') values (' + params + ') returning *', keys.map((k) => parsed.data[k]));`,
        `    return c.json(${rowName}.parse(rows[0]), 201);`,
        "  });",
      );
    }
    lines.push("  return app;", "}");

    const importNames = table.kind === "table" ? `${rowName}, ${insertName}` : rowName;
    return {
      imports: [
        { from: "hono", names: ["Hono"] },
        { from: `${importPath}/${fileBaseName(table, snapshot)}.mjs`, names: [importNames] },
      ],
      body: lines.join("\n"),
      exportName: exportNameFor(table, snapshot),
    };
  }

  renderTypes(table: Table, snapshot: Snapshot, _opts: RestTargetOptions): string {
    const name = exportNameFor(table, snapshot);
    return [
      "// Generated by supawatch. Do not edit.",
      'import type { Hono } from "hono";',
      `export declare function ${name}(sql: { unsafe(text: string, params?: unknown[]): Promise<any[]> }): Hono;`,
      "",
    ].join("\n");
  }
}

export default RestTarget;
