import type {
  Snapshot,
  SnapshotFile,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits mcp-server.mjs: a factory building an MCP server with list and
// get tools per table, input-validated by the already-generated Zod
// schemas. Every AI-adjacent team hand-writes exactly this against their
// database, and theirs drifts; this one regenerates on every schema
// change. The consumer supplies the SDK server instance environment via
// peer dependency and connects a transport themselves.

export interface McpTargetOptions extends TargetOptions {
  schemasImportPath?: string;
}

function baseNameFor(table: Table): string {
  return table.name.replace(/[^a-zA-Z0-9_]/g, "_");
}

function quotedIdent(table: Table): string {
  const q = (s: string) => '"' + s.replace(/"/g, '""') + '"';
  return `${q(table.schema)}.${q(table.name)}`;
}

export class McpTarget implements Target<McpTargetOptions> {
  readonly name = "mcp";
  readonly fileExtension = ".mjs";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("mcp is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, opts: McpTargetOptions): SnapshotFile[] {
    const importPath = opts.schemasImportPath ?? "./zod";
    const tables = snapshot.tables.filter((t) => t.kind === "table");

    const lines: string[] = [
      "// Generated by supawatch. Do not edit.",
      'import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";',
      'import { z } from "zod";',
    ];
    for (const table of tables) {
      lines.push(
        `import { ${baseNameFor(table)}Row } from ${JSON.stringify(`${importPath}/${table.name}.mjs`)};`,
      );
    }
    lines.push(
      "",
      "export function createMcpServer({ sql, name = \"supawatch-db\", version = \"0.0.0\" }) {",
      "  const server = new McpServer({ name, version });",
    );
    for (const table of tables) {
      const base = baseNameFor(table);
      const ident = quotedIdent(table);
      lines.push(
        `  server.tool(`,
        `    ${JSON.stringify(`${base}_list`)},`,
        `    ${JSON.stringify(`List rows from ${table.schema}.${table.name}`)},`,
        "    { limit: z.number().int().min(1).max(100).optional() },",
        "    async ({ limit }) => {",
        `      const rows = await sql.unsafe('select * from ${ident} limit ' + Math.min(limit ?? 20, 100));`,
        `      const parsed = rows.map((row) => ${base}Row.parse(row));`,
        "      return { content: [{ type: \"text\", text: JSON.stringify(parsed, null, 2) }] };",
        "    },",
        "  );",
      );
      if (table.primaryKey.length === 1) {
        const pk = table.primaryKey[0];
        const pkIdent = '"' + pk.replace(/"/g, '""') + '"';
        lines.push(
          `  server.tool(`,
          `    ${JSON.stringify(`${base}_get`)},`,
          `    ${JSON.stringify(`Fetch one row from ${table.schema}.${table.name} by ${pk}`)},`,
          `    ${base}Row.pick({ ${JSON.stringify(pk)}: true }).shape,`,
          "    async (input) => {",
          `      const rows = await sql.unsafe('select * from ${ident} where ${pkIdent} = $1 limit 1', [input[${JSON.stringify(pk)}]]);`,
          `      const row = rows.length > 0 ? ${base}Row.parse(rows[0]) : null;`,
          "      return { content: [{ type: \"text\", text: JSON.stringify(row, null, 2) }] };",
          "    },",
          "  );",
        );
      }
    }
    lines.push("  return server;", "}", "");
    return [{ file: "mcp-server.mjs", content: lines.join("\n") }];
  }
}

export default McpTarget;
