import { pathToFileURL } from "node:url";
import type {
  Column,
  Rendered,
  RuntimeType,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
  Verdict,
  Verifier,
} from "@supawatch/core";

export interface ZodTargetOptions extends TargetOptions {
  strict?: boolean;
}

function zodExpr(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return runtime.integer ? "z.number().int()" : "z.number()";
    case "string":
      return runtime.format === "uuid" ? "z.uuid()" : "z.string()";
    case "boolean":
      return "z.boolean()";
    case "date":
      return "z.date()";
    case "json":
    case "unknown":
      return "z.unknown()";
    case "enum": {
      const labels = runtime.labels.map((l) => JSON.stringify(l)).join(", ");
      return `z.enum([${labels}])`;
    }
  }
}

// The TypeScript type the driver-truth runtime implies, for the .d.mts.
function tsType(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "json":
    case "unknown":
      return "unknown";
    case "enum":
      return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
  }
}

export function exportNameFor(table: Table): string {
  return table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "Row";
}

function fieldSchema(col: Column): string {
  let s = zodExpr(col.runtime);
  if (col.nullable) s += ".nullable()";
  return s;
}

function fieldType(col: Column): string {
  const base = tsType(col.runtime);
  // unknown already absorbs null; adding the union is noise.
  if (col.nullable && base !== "unknown") return `${base} | null`;
  return base;
}

export class ZodTarget implements Target<ZodTargetOptions> {
  readonly name = "zod";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: true,
    brandedTypes: true,
    dateInstances: true,
  };

  renderTable(table: Table, _snapshot: Snapshot, opts: ZodTargetOptions): Rendered {
    const strict = opts.strict !== false;
    const ctor = strict ? "z.strictObject" : "z.object";
    const fields = table.columns
      .map((col) => `  ${JSON.stringify(col.name)}: ${fieldSchema(col)},`)
      .join("\n");
    return {
      imports: [{ from: "zod", names: ["z"] }],
      body: `export const ${exportNameFor(table)} = ${ctor}({\n${fields}\n});`,
      exportName: exportNameFor(table),
    };
  }

  // Companion .d.mts so consumers get a typed parse and a Row type even
  // though the runtime artifact is plain JavaScript.
  renderTypes(table: Table, _snapshot: Snapshot, _opts: ZodTargetOptions): string {
    const name = exportNameFor(table);
    const rowType = table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "RowType";
    const fields = table.columns
      .map((col) => `  ${JSON.stringify(col.name)}: ${fieldType(col)};`)
      .join("\n");
    return [
      "// Generated by supawatch. Do not edit.",
      'import { z } from "zod";',
      "",
      `export type ${rowType} = {`,
      fields,
      "};",
      `export declare const ${name}: z.ZodType<${rowType}>;`,
      "",
    ].join("\n");
  }

  verifier(): Verifier {
    return {
      async load(file: string, exportName: string): Promise<unknown> {
        const url = pathToFileURL(file).href + `?v=${Date.now()}`;
        const mod = (await import(url)) as Record<string, unknown>;
        const schema = mod[exportName];
        if (!schema) {
          throw new Error(
            `no export ${exportName} in ${file}; exports: ${Object.keys(mod).join(",")}`,
          );
        }
        return schema;
      },
      check(schema: unknown, value: unknown): Verdict {
        const s = schema as {
          safeParse(v: unknown): {
            success: boolean;
            error?: { issues: { message: string }[] };
          };
        };
        const r = s.safeParse(value);
        if (r.success) return { ok: true };
        return { ok: false, reason: r.error?.issues[0]?.message };
      },
    };
  }
}

export default ZodTarget;
