import type {
  RuntimeType,
  Snapshot,
  SnapshotFile,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";
import { exportBaseName, fileBaseName } from "@supawatch/core";

// Emits graphql-schema.mjs: a Pothos builder wiring one object type per
// table with per-table list and byId queries over postgres.js. Field
// types follow driver truth (numeric is a String, timestamps are
// serialized to ISO strings). API verified empirically against
// @pothos/core 4.13 (objectRef.implement, queryType, toSchema).

export type GraphqlTargetOptions = TargetOptions;

function pothosField(runtime: RuntimeType): { method: string; wrap: (r: string) => string } {
  switch (runtime.kind) {
    case "number":
      return runtime.integer
        ? { method: "int", wrap: (r) => `Number(${r})` }
        : { method: "float", wrap: (r) => `Number(${r})` };
    case "boolean":
      return { method: "boolean", wrap: (r) => r };
    case "date":
      return { method: "string", wrap: (r) => `${r} instanceof Date ? ${r}.toISOString() : ${r}` };
    default:
      // strings, enums (labels), json/unknown/bytes/arrays serialize
      // via String or JSON below; keep GraphQL surface simple.
      return { method: "string", wrap: (r) => `typeof ${r} === "string" ? ${r} : JSON.stringify(${r})` };
  }
}

function baseNameFor(table: Table, snapshot: Snapshot): string {
  return exportBaseName(table, snapshot);
}

function quotedIdent(table: Table): string {
  const q = (s: string) => '"' + s.replace(/"/g, '""') + '"';
  return `${q(table.schema)}.${q(table.name)}`;
}

export class GraphqlTarget implements Target<GraphqlTargetOptions> {
  readonly name = "graphql";
  readonly fileExtension = ".mjs";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("graphql is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: GraphqlTargetOptions): SnapshotFile[] {
    const tables = snapshot.tables.filter((t) => t.kind === "table");
    const lines: string[] = [
      "// Generated by supawatch. Do not edit.",
      'import SchemaBuilder from "@pothos/core";',
      "",
      "export function createGraphqlSchema(sql) {",
      "  const builder = new SchemaBuilder({});",
    ];
    for (const table of tables) {
      const base = baseNameFor(table, snapshot);
      lines.push(
        `  const ${base}Ref = builder.objectRef(${JSON.stringify(base)});`,
        `  ${base}Ref.implement({`,
        "    fields: (t) => ({",
      );
      for (const col of table.columns) {
        const f = pothosField(col.runtime);
        const access = `p[${JSON.stringify(col.name)}]`;
        lines.push(
          `      ${col.name.replace(/[^a-zA-Z0-9_]/g, "_")}: t.${f.method}({ nullable: ${col.nullable}, resolve: (p) => ${col.nullable} && ${access} === null ? null : (${f.wrap(access)}) }),`,
        );
      }
      lines.push("    }),", "  });");
    }
    lines.push("  builder.queryType({", "    fields: (t) => ({");
    for (const table of tables) {
      const base = baseNameFor(table, snapshot);
      const ident = quotedIdent(table);
      const field = exportBaseName(table, snapshot);
      lines.push(
        `      ${field}: t.field({`,
        `        type: [${base}Ref],`,
        "        resolve: async () => {",
        `          return await sql.unsafe('select * from ${ident} limit 100');`,
        "        },",
        "      }),",
      );
    }
    lines.push("    }),", "  });", "  return builder.toSchema();", "}", "");
    return [{ file: "graphql-schema.mjs", content: lines.join("\n") }];
  }
}

export default GraphqlTarget;
