import { pathToFileURL } from "node:url";
import * as v from "valibot";
import type {
  Column,
  Rendered,
  RuntimeType,
  Snapshot,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
  Verdict,
  Verifier,
} from "@supawatch/core";

export interface ValibotTargetOptions extends TargetOptions {
  strict?: boolean;
}

function valibotExpr(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return runtime.integer
        ? "v.pipe(v.number(), v.integer())"
        : "v.number()";
    case "string":
      return runtime.format === "uuid"
        ? "v.pipe(v.string(), v.uuid())"
        : "v.string()";
    case "boolean":
      return "v.boolean()";
    case "date":
      return "v.date()";
    case "bytes":
      return "v.instance(Uint8Array)";
    case "json":
    case "unknown":
      return "v.unknown()";
    case "array":
      return `v.array(${valibotExpr(runtime.element)})`;
    case "enum": {
      const labels = runtime.labels.map((l) => JSON.stringify(l)).join(", ");
      return `v.picklist([${labels}])`;
    }
  }
}

function tsType(runtime: RuntimeType): string {
  switch (runtime.kind) {
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
    case "bytes":
      return "Uint8Array";
    case "json":
    case "unknown":
      return "unknown";
    case "array": {
      const el = tsType(runtime.element);
      return el.includes("|") ? `(${el})[]` : `${el}[]`;
    }
    case "enum":
      return runtime.labels.map((l) => JSON.stringify(l)).join(" | ");
  }
}

export function exportNameFor(table: Table): string {
  return table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "Row";
}

function fieldSchema(col: Column): string {
  const base = valibotExpr(col.runtime);
  return col.nullable ? `v.nullable(${base})` : base;
}

export class ValibotTarget implements Target<ValibotTargetOptions> {
  readonly name = "valibot";
  readonly fileExtension = ".mjs";
  readonly capabilities: TargetCapabilities = {
    strictObjects: true,
    brandedTypes: true,
    dateInstances: true,
  };

  renderTable(
    table: Table,
    _snapshot: Snapshot,
    opts: ValibotTargetOptions,
  ): Rendered {
    const strict = opts.strict !== false;
    const ctor = strict ? "v.strictObject" : "v.object";
    const fields = table.columns
      .map((col) => `  ${JSON.stringify(col.name)}: ${fieldSchema(col)},`)
      .join("\n");
    return {
      imports: [{ from: "valibot", namespace: "v" }],
      body: `export const ${exportNameFor(table)} = ${ctor}({\n${fields}\n});`,
      exportName: exportNameFor(table),
    };
  }

  renderTypes(table: Table, _snapshot: Snapshot, _opts: ValibotTargetOptions): string {
    const name = exportNameFor(table);
    const rowType = table.name.replace(/[^a-zA-Z0-9_]/g, "_") + "RowType";
    const fields = table.columns
      .map((col) => {
        const base = tsType(col.runtime);
        const t = col.nullable && base !== "unknown" ? `${base} | null` : base;
        return `  ${JSON.stringify(col.name)}: ${t};`;
      })
      .join("\n");
    return [
      "// Generated by supawatch. Do not edit.",
      'import type { GenericSchema } from "valibot";',
      "",
      `export type ${rowType} = {`,
      fields,
      "};",
      `export declare const ${name}: GenericSchema<unknown, ${rowType}>;`,
      "",
    ].join("\n");
  }

  verifier(): Verifier {
    return {
      async load(file: string, exportName: string): Promise<unknown> {
        const url = pathToFileURL(file).href + `?v=${Date.now()}`;
        const mod = (await import(url)) as Record<string, unknown>;
        const schema = mod[exportName];
        if (!schema) {
          throw new Error(
            `no export ${exportName} in ${file}; exports: ${Object.keys(mod).join(",")}`,
          );
        }
        return schema;
      },
      check(schema: unknown, value: unknown): Verdict {
        // Uses this package's own valibot to run a schema built by the
        // consumer's copy; safe within the same major.
        const r = v.safeParse(schema as v.GenericSchema, value);
        if (r.success) return { ok: true };
        return { ok: false, reason: r.issues[0]?.message };
      },
    };
  }
}

export default ValibotTarget;
