import type {
  Snapshot,
  SnapshotFile,
  Table,
  Target,
  TargetCapabilities,
  TargetOptions,
} from "@supawatch/core";

// Emits rls-skeletons.sql: policy stubs for tables that have RLS
// enabled but no policies, or RLS disabled entirely. Owner and tenant
// columns are detected by name heuristics and drive the stub shape; a
// human finishes each policy, the generator never pretends to know
// intent. Tables already fully covered are listed, not restubbed.

export type RlsTargetOptions = TargetOptions;

const OWNER_COLUMNS = ["user_id", "owner_id", "author_id", "created_by", "profile_id"];
const TENANT_COLUMNS = ["tenant_id", "org_id", "organization_id", "workspace_id", "team_id"];

function detect(table: Table, names: string[]): string | null {
  for (const n of names) {
    if (table.columns.some((c) => c.name === n)) return n;
  }
  return null;
}

export class RlsTarget implements Target<RlsTargetOptions> {
  readonly name = "rls";
  readonly fileExtension = ".sql";
  readonly barrel = false;
  readonly capabilities: TargetCapabilities = {
    strictObjects: false,
    brandedTypes: false,
    dateInstances: false,
  };

  renderTable(): never {
    throw new Error("rls is a snapshot-level target");
  }

  renderSnapshot(snapshot: Snapshot, _opts: RlsTargetOptions): SnapshotFile[] {
    const lines: string[] = [
      "-- Generated by supawatch. Do not edit generated stubs in place;",
      "-- copy them into a migration and finish the TODO conditions.",
      "-- Heuristic column detection only: the generator cannot know intent.",
      "",
    ];

    const tables = snapshot.tables.filter((t) => t.kind === "table");
    for (const table of tables) {
      const q = (s: string) => '"' + s.replace(/"/g, '""') + '"';
      const ident = `${q(table.schema)}.${q(table.name)}`;

      if (table.rlsEnabled && table.policies.length > 0) {
        lines.push(
          `-- ${table.schema}.${table.name}: rls enabled, ${table.policies.length} policies exist (${table.policies.map((p) => p.name).join(", ")}); nothing generated`,
          "",
        );
        continue;
      }

      const owner = detect(table, OWNER_COLUMNS);
      const tenant = detect(table, TENANT_COLUMNS);

      lines.push(`-- ${table.schema}.${table.name}`);
      if (!table.rlsEnabled) {
        lines.push(`alter table ${ident} enable row level security;`);
      }
      if (owner) {
        lines.push(
          `create policy "${table.name}_select_own" on ${ident}`,
          `  for select to authenticated`,
          `  using ((select auth.uid()) = ${q(owner)});`,
          `create policy "${table.name}_write_own" on ${ident}`,
          `  for all to authenticated`,
          `  using ((select auth.uid()) = ${q(owner)})`,
          `  with check ((select auth.uid()) = ${q(owner)});`,
        );
      } else if (tenant) {
        lines.push(
          `create policy "${table.name}_tenant_isolation" on ${ident}`,
          `  for all to authenticated`,
          `  using (${q(tenant)} = (select (auth.jwt() -> 'app_metadata' ->> 'tenant_id')::uuid)) -- TODO: confirm the tenant claim path and type`,
          `  with check (${q(tenant)} = (select (auth.jwt() -> 'app_metadata' ->> 'tenant_id')::uuid));`,
        );
      } else {
        lines.push(
          `-- TODO: no owner or tenant column detected (looked for: ${[...OWNER_COLUMNS, ...TENANT_COLUMNS].join(", ")})`,
          `-- create policy "${table.name}_policy" on ${ident} for select to authenticated using (TODO);`,
        );
      }
      lines.push("");
    }

    return [{ file: "rls-skeletons.sql", content: lines.join("\n") }];
  }
}

export default RlsTarget;
